var wordlist1 = [
    'attrition',
    'transmute',
    'hegemony',
    'elusive',
    'evanescent',
    'irk',
    'steadfast',
    'recrudescence',
    'perfidy',
    'vindictive',
    'underscore',
    'hail',
    'apposite',
    'forthright',
    'reverent',
    'abstruse',
    'lethargy',
    'vapid',
    'recrimination',
    'supplicate',
    'stalwart',
    'iconoclast',
    'byzantine',
    'sedentary',
    'inviolable',
    'avert',
    'trite',
    'pragmatic',
    'imperturbable',
    'precedent',
    'obscure',
    'magnate',
    'preempt',
    'sanguine',
    'invective',
    'noisome',
    'vacuous',
    'devolve',
    'pellucid',
    'indigent',
    'awry',
    'uncanny',
    'contemptuous',
    'stupefy',
    'exemplify',
    'audacious',
    'gratuitous',
    'flag',
    'supplant',
    'duplicate',
    'turbid',
    'propitious',
    'lacerate',
    'impervious',
    'prepossessing',
    'conflate',
    'evoke',
    'avarice',
    'imprudent',
    'deter',
    'ornate',
    'fetid',
    'castigate',
    'fetter',
    'germane',
    'vaunted',
    'spendthrift',
    'profuse',
    'paradigm',
    'paucity',
    'perplex',
    'avow',
    'malevolent',
    'idolatry',
    'abet',
    'kowtow',
    'deliberate',
    'allocate',
    'unstinting',
    'goad'
];

var wordlist2 = [
     'autonomous',
     'foible',
     'indolent',
     'limpid',
     'assiduous',
     'recant',
     'culminate',
     'oblique',
     'deferential',
     'malady',
     'canard',
     'cupidity',
     'assimilate',
     'unnerve',
     'alacrity',
     'gregarious',
     'expound',
     'retract',
     'zealous',
     'obstreperous',
     'perennial',
     'protract',
     'censure',
     'pith',
     'tempestuous',
     'inquisitive',
     'contingent',
     'pristine',
     'lament',
     'coeval',
     'voracious',
     'mollify',
     'polemical',
     'accede',
     'heretical',
     'espouse',
     'quandary',
     'tractable',
     'whimsical',
     'tantamount',
     'narcissism',
     'banal',
     'obviate',
     'frugal',
     'equanimity',
     'cow',
     'constituent',
     'canonical',
     'eradicate',
     'sage',
     'catalyst',
     'protean',
     'decry',
     'extenuate',
     'indict',
     'wanting',
     'evasive',
     'diffident',
     'jaded',
     'palliate',
     'sly',
     'apprehension',
     'myriad',
     'commodious',
     'fractious',
     'variegated',
     'turpitude',
     'sporadic',
     'amalgamate',
     'nicety',
     'nascent',
     'legacy',
     'disparate',
     'parody',
     'assuage',
     'profligate',
     'subtle',
     'undermine',
     'obeisance',
     'disinterested'
];

var wordlist3 = [
    'fundamental',
    'conviction',
    'aptitude',
    'repugnance',
    'ignorance',
    'flout',
    'adventurous',
    'frivolous',
    'willful',
    'irrational',
    'vulnerable',
    'presume ',
    'cynical ',
    'disinterested ',
    'ramification ',
    'undermine ',
    'divert ',
    'redeem ',
    'preserve ',
    'preempt ',
    'quantifiable ',
    'inexhaustible ',
    'remarkable ',
    'benefactor ',
    'precedent ',
    'surrogate',
    'well-intentioned',
    'relieved',
    'detain',
];

var wordlist4 = [
    'paradox',
    'predominant',
    'tranquil',
    'serene',
    'agitate',
    'comprehensive',
    'deprecate',
    'congenial',
    'disdain',
    'deference',
    'insular',
    'synoptic',
    'sensational',
    'exceptional',
    'transitional',
    'segregate',
    'overshadow',
    'congruous',
    'dichotomy',
    'reciprocity',
    'subordinate',
    'facilitate',
    'avert',
    'repress',
    'nonplus',
    'caustic',
    'humiliate',
    'discomfit',
    'delude',
    'tantalize',
    'divest',
    'regal',
    'forfeit',
    'debase'
];

var wordlist5 = [
    'banal',
    'heretical',
    'embroider',
    'obstinate',
    'credulity',
    'palatable',
    'conspicuous',
    'hoard',
    'trample',
    'retrieve',
    'elementary',
    'presumptuous',
    'dividend',
    'perennial',
    'archetype',
    'captious',
    'intimidate',
    'poise',
    'compromise',
    'forestall',
    'stiff',
    'protest'
];

var wordlist6 = [
    'supernatural',
    'elucidate',
    'artless',
    'authentic',
    'whimsy',
    'deity',
    'avenge',
    'weary',
    'ingenuous',
    'solicitous',
    'vindictive',
    'dispassionate',
    'meager',
    'commensurate',
    'substantiate',
    'circumscribe',
    'unworldly',
    'ethos',
    'perfume',
    'entitle',
    'deprive',
    'conspiracy',
    'collective',
    'discrete',
    'extrapolate',
    'transcribe',
    'amplify',
    'waggish',
    'siren',
    'dispel',
    'attentive',
    'inquisitive',
    'receptive',
    'distinctive'
];

var wordlist7 = [
    'spell',
    'plethora',
    'moratorium',
    'reciprocation',
    'discredit',
    'overwhelming',
    'joint',
    'tailor',
    'address',
    'conform',
    'vicious',
    'intricate',
    'entity',
    'convoluted',
    'amorphous',
    'illusory',
    'yearn',
    'meditative',
    'tepid',
    'onset',
    'falter',
    'dwindle',
    'dampen',
];

var wordlist8 = [
    'dominate',
    'impressionable',
    'naive',
    'obstinate',
    'decisive',
    'ingenious',
    'resolve',
    'arcane',
    'whimsy',
    'inspire',
    'provoke',
    'catalyst',
    'disguise',
    'impede',
    'consummate',
    'precipitate',
    'comprehensive',
    'spot',
    'verifiable',
    'salient',
    'outmoded'
];

var wordlist9 = [
    'reflective',
    'enamor',
    'delicate',
    'synthesis',
    'reconnaissance',
    'flaccid',
    'treacherous',
    'prestigious',
    'sedentary',
    'distribution',
    'salvage',
    'procure',
    'ascendancy',
    'decimate',
    'denigrate',
    'resurrect',
    'jockey',
    'revive',
    'emerge',
    'flag',
    'riveting',
    'connive',
    'underrate',
    'transcendental',
    'hatred',
    'contest',
    'aggrandize',
    'embellish',
    'jeopardize'
];

var wordlist10 = [
    'arbitrary',
    'equivocal',
    'cannibalism',
    'ferret',
    'prey',
    'permissive',
    'explicit',
    'garrulous',
    'excoriate',
    'bombast',
    'euphemism',
    'obsolete',
    'constant',
    'epitome',
    'bizarre',
    'eccentric',
    'urbane',
    'coarse',
    'faction',
    'uniform',
    'spectacular',
    'linger',
];

var wordlist11 = [
    'sketch',
    'impetuous',
    'sarcasm',
    'mockery',
    'contempt',
    'condescension',
    'maverick',
    'authoritative',
    'articulate',
    'reiterate',
    'complaisance',
    'gallantry',
    'poignant',
    'plaintive',
    'laudable',
    'craven',
    'idiosyncrasy',
    'precursor',
    'compatible'
];

var wordlist12 = [
    'interim',
    'hitherto',
    'ossify',
    'misdeed',
    'coerce',
    'intimidate',
    'blithe',
    'incubate',
    'domestic',
    'lackluster',
    'feckless',
    'caricature',
    'salvation',
    'throwback',
    'aberration',
    'personification',
    'extol',
    'transmute',
    'inure',
    'impassive',
    'resent',
    'apprehension',
    'formidable',
    'ferocity',
    'adversity',
    'exacerbate',
    'eradicate',
    'ameliorate',
    'parable',
    'illustrate'
];

var wordlist13 = [
    'circumspect',
    'reluctant',
    'nonplus',
    'obsequious',
    'intransigent',
    'deference',
    'negligent',
    'ethical',
    'alternative',
    'marvelous',
    'efficient',
    'virtuosity',
    'democratic',
    'provincial',
    'revolutionary',
    'finite',
    'assiduous',
    'maintenance',
    'hostile',
    'revile',
    'scrutinize',
    'neglect',
    'disjunction',
    'remuneration',
    'intricacy',
    'futile',
    'decadent',
];

var wordlist14 = [
    'confirm',
    'syntactic',
    'economical',
    'shift',
    'protest',
    'flamboyant',
    'drab',
    'sordid',
    'discourteous',
    'kin',
    'merge',
    'hierarchy',
    'hunch',
    'deduction',
    'majestic',
    'deter',
    'displace',
    'manifest',
    'plausible',
    'rudimentary',
    'reconcile',
    'acerbic',
    'onerous',
    'reluctant'
];

var wordlist15 = [
    'attain',
    'definitive',
    'rigorous',
    'antidote',
    'deter',
    'counterpart',
    'disciple',
    'reserve',
    'diffident',
    'contentious',
    'facetious',
    'presumptuous',
    'intrepid',
    'clannish',
    'tranquil',
    'sprawl',
    'discredit',
    'repudiate',
    'condone',
    'placate',
    'emulate',
    'locus',
    'mundane',
    'assail',
    'exhilarate',
    'overwhelm',
    'contrive',
    'prolific'
];

var wordlist16 = [
    'extensive',
    'forage',
    'recede',
    'sequential',
    'integrity',
    'transmit',
    'manipulate',
    'aggrandize',
    'arcane',
    'explicit',
    'unimpeachable',
    'defy',
    'inform',
    'inveterate',
    'proprietary',
    'ridicule',
    'antagonize',
    'authoritarian',
    'modicum',
    'dissent',
    'demur',
    'schism',
    'cater',
    'flout',
    'elude',
];

var wordlist17 = [
    'indispensable',
    'discrete',
    'preeminent',
    'pertinent',
    'innuendo',
    'insult',
    'blunt',
    'boisterous',
    'fallacious',
    'embellish',
    'preclude',
    'initiate',
    'inhibit',
    'evasive',
    'forthright',
    'paradigm',
    'misnomer',
    'profound',
    'anomaly',
    'alienate',
    'antagonize',
    'intimidate',
    'mollify',
    'prompt',
    'coincidental',
    'ironic',
    'dismay',
    'disparage'
];

var wordlist18 = [
    'resemble',
    'decry',
    'applaud',
    'elucidate',
    'obviate',
    'daunting',
    'dazzle',
    'authenticate',
    'imbue',
    'revise',
    'disseminate',
    'underplay',
    'laud',
    'discursive',
    'hedonism',
    'devoid',
    'intrigue',
    'covet',
    'resent'
];

var wordlist19 = [
    'dismal',
    'falter',
    'liable',
    'render',
    'arbitrary',
    'superfluous',
    'pragmatic',
    'adventurous',
    'empirical',
    'plausible',
    'grandiose',
    'vernacular',
    'dissect',
    'dismiss',
    'improvise',
    'culmination',
    'veneration',
    'burgeon',
    'misanthropy',
    'equanimity',
    'prodigal',
    'vigorous',
    'belie',
    'exacerbate'
];

var wordlist20 = [
    'laudable',
    'authentic',
    'futile',
    'introspection',
    'exuberant',
    'idiosyncrasy',
    'prolific',
    'sedentary',
    'sluggish',
    'measured',
    'restive',
    'elaborate',
    'discern',
    'peripheral',
    'contiguous',
    'analogous',
    'ingenious',
    'ruse',
    'contrive',
    'forbear',
    'divisive',
    'seductive',
    'qualify',
    'haphazard',
    'fleeting',
    'obsolete',
    'quaint',
    'defer',
    'confer',
    'exalt',
    'disdain'
];

var wordlist21 = [
    'impose',
    'toll',
    'ameliorate',
    'consensus',
    'judicious',
    'incisive',
    'polarity',
    'surrender',
    'anarchy',
    'tyranny',
    'autonomy',
    'illusory',
    'esoteric',
    'literal',
    'latent',
    'allusion',
    'axiomatic',
    'portentous',
    'scathing',
    'incongruous'
];

var wordlist22 = [
    'transition',
    'mandatory',
    'verify',
    'annihilate',
    'adduce',
    'concede',
    'unwitting',
    'vicarious',
    'haphazard',
    'counterbalance',
    'sacrilege',
    'intractable',
    'incontrovertible',
    'equipoise',
    'oscillate',
    'inadvertent',
    'remote'
];

var wordlist23 = [
    'witticism',
    'scintillating',
    'perspicuous',
    'stultify',
    'facetious',
    'hazardous',
    'pejorative',
    'amorphous',
    'exclude',
    'imminent',
    'scrutinize',
    'deride',
    'pious',
    'divert',
    'whimsy',
    'beneficiary',
    'ennui',
    'upheaval',
    'tranquil',
    'liability',
    'preciosity',
    'buffoonery',
    'melodrama',
];

var wordlist24 = [
    'monotonous',
    'virtual',
    'proprietary',
    'requisite',
    'heed',
    'condone',
    'iconoclastic',
    'reckless',
    'imperious',
    'penitential',
    'prolixity',
    'impetuous',
    'taciturn',
    'pellucid',
    'volatile',
    'partial',
    'prosaic',
    'eccentric',
    'phony',
    'harbinger',
    'prophetic',
    'outset',
    'appropriation',
    'incessant',
    'delineate',
    'compromise',
    'acumen',
    'agonize',
    'reverence',
    'fastidious',
    'didactic',
    'belie',
    'overshadow',
    'unsparing',
    'circumscribe',
    'trifling',
    'allegation'
];

var wordlist25 = [
    'reconcile',
    'improvise',
    'endorse',
    'row',
    'accord',
    'predicament',
    'fester',
    'distort',
    'incentive',
    'bogus',
    'obsolete',
    'congruous',
    'fortuitous',
    'cynical',
    'conjure',
    'covet',
    'exacerbate',
    'authorization',
    'comprehensive',
    'pithy',
    'deem',
    'yield',
    'scrutinize',
    'capricious',
    'corroborate',
    'debunk',
    'novice',
    'involved',
    'considerable',
    'equitable',
    'fortuitous',
    'shrug',
    'ameliorate',
    'ascertain'
];

var wordlist26 = [
    'evasive',
    'misnomer',
    'anomaly',
    'imperceptible',
    'relentless',
    'susceptible',
    'render',
    'soporific',
    'lucid',
    'colloquial',
    'pedantic',
    'disseminate',
    'demanding',
    'scathing',
    'frugality',
    'stingy',
    'thrift',
    'disaffection',
    'dislocation',
    'deteriorate',
    'midst',
    'forthright',
    'paradigm',
    'profundity',
    'precarious',
    'untenable',
    'compelling',
    'compliment',
    'pan',
    'tedious',
    'bearing',
    'exacting',
    'copious',
    'miserly',
    'subversion',
    'estrange'
];

var wordlist27 = [
    'mettlesome',
    'initiative',
    'eliminate',
    'caprices',
    'sordid',
    'acerbic',
    'hunch',
    'circumvent',
    'denote',
    'metaphor',
    'inherent',
    'conjecture',
    'sensibly',
    'prodigy',
    'veiled',
    'purify',
    'heroic',
    'replicated',
    'pity',
    'meticulous',
    'imminent',
    'respecter',
    'compassion',
    'level',
];

var wordlist28 = [
    'unidimensional',
    'ballyhoo',
    'quip',
    'pensive',
    'droll',
    'stoicism',
    'fastidious',
    'congenial',
    'sound',
    'intriguing',
    'retroactive',
    'slacken',
    'dampen',
    'drag',
    'panacea',
    'collapse',
    'tout',
    'tenuous',
    'legitimate',
    'augment',
    'disgorge',
    'qualitative',
    'surplus',
    'avert',
    'forestall',
    'endure',
    'presage',
    'portend',
    'clandestine',
    'perilous',
    'covert',
    'exhilarate',
    'rudimentary',
    'heterogeneous',
];

var wordlist29 = [
    'mercurial',
    'phlegmatic',
    'apathetic',
    'cunning',
    'blithe',
    'authoritarian',
    'histrionic',
    'megalomania',
    'egalitarian',
    'indolent',
    'charismatic',
    'prognosis',
    'auspicious',
    'circuitous',
    'comprehensive',
    'spontaneous',
    'glib',
    'veracious',
    'vivacious',
    'forge',
    'spurn',
    'clique',
    'cluster',
    'inert',
    'jubilant',
    'sensuous',
    'enervate',
    'foreground',
    'circumvent',
    'neophyte',
    'novice',
    'pragmatism',
    'zealot',
    'meddle',
    'expeditious',
    'pecuniary',
    'sluggish',
    'capricious',
    'dilatory',
    'scrupulous',
    'mendacity',
    'meticulous'
];

var wordlist30 = [
    'speculation',
    'extraneous',
    'demonstrable',
    'transcendent',
    'aver',
    'feign',
    'avow',
    'lopsided',
    'feeble',
    'robust',
    'turbulent',
    'lethargic',
    'fervor',
    'hybrid',
    'indiscriminate',
    'conciliate',
    'exhaustive',
    'glib',
    'veracious',
    'vivacious',
    'substantial',
    'prestigious',
    'anomalous',
    'affinity',
    'objection',
    'opaque',
    'pugnacious',
    'deliberate',
    'punctilious',
    'courteous',
    'complacent',
    'truculent',
    'myriad',
    'attest',
    'heterogeneous',
    'indeterminate',
    'champion',
    'downplay'
];

var wordlist31 = [
    'pedestrian',
    'esoteric',
    'compelling',
    'mercenary',
    'paradigm',
    'contentious',
    'authoritarian',
    'forbear',
    'volatile',
    'lucid',
    'assault',
    'bewilder',
    'fray',
    'provocative',
    'cynical',
    'captivate',
    'outrage',
    'tenuous',
    'anchor',
    'apt',
    'absurd',
    'marginal',
    'profound',
    'taint',
    'hinder',
    'supersede',
    'inhibit',
    'proscribe',
    'confine',
    'multifarious',
    'onerous',
    'circumscribe',
    'taxing',
    'forbidding',
    'placid',
    'daunting'
];

var wordlist32 = [
    'discrete',
    'confused',
    'perfunctory',
    'overt',
    'exacting',
    'ballyhoo',
    'quip',
    'pensive',
    'droll',
    'stoicism',
    'hectic',
    'demanding',
    'dilatory',
    'averse',
    'empiricism',
    'utilitarian',
    'parochialism',
    'irk',
    'flippancy',
    'subtle',
    'discursive',
    'obsequious',
    'discreet',
    'sabotage',
    'acquiesce',
    'intractable',
    'veneration',
    'detestation',
    'grant',
    'refute',
    'defy',
    'rosy',
    'encomium',
    'tribute',
    'nullify'
];

var wordlist33 = [
    'deceptive',
    'plastic',
    'potency',
    'encumber',
    'replete',
    'discretionary',
    'bureaucracy',
    'skirt',
    'scrutinize',
    'counter',
    'revelation',
    'stigma',
    'allure',
    'blemish',
    'inveterate',
    'intercept',
    'oblige',
    'suffocate',
    'monitor',
    'commend',
    'weird',
    'shackle',
    'admonish',
    'hazardous',
    'momentous',
    'precarious',
    'stagnate',
    'rigid',
    'repudiate',
    'recant',
    'neutral',
    'betray',
    'expel',
    'endorse',
    'oust',
    'sanction'
];

var wordlist34 = [
    '"proprietary',
    'impenetrable',
    'didactic',
    'paradox',
    'cosmopolitan',
    'capricious',
    'mercenary',
    'intransigent',
    'scathing',
    'satirize',
    'abhor',
    'relish',
    'enchanting',
    'flout',
    'subvert',
    'palpable',
    'temperate',
    'delegate',
    'ascribe',
    'sophisticated',
    'consensus',
    'compunction',
    'dichotomy',
    'untenable',
    'bypass',
    'magnify',
    'circumvent',
    'evanescent',
    'demise',
    'transient',
    'decay',
    'deteriorate',
    'conspicuous',
    'intriguing',
    'trifling',
    'deleterious',
];

var wordlist35 = [
    'elephantine',
    'ubiquity',
    'promise',
    'gainsay',
    'sterling',
    'ad hoc',
    'anonymous',
    'evenhanded',
    'confessional',
    'amplify',
    'particularize',
    'encase',
    'fleeting',
    'incompatible',
    'cluster',
    'stratify',
    'innocuous',
    'overture',
    'bleak',
    'belie',
    'undercut',
    'prefigure',
    'entail',
    'coincident',
    'hack',
    'generic',
    'inclusive'
];

var wordlist36 = [
    'cultivate',
    'irascible',
    'abstemious',
    'contentious',
    'surreptitious',
    'insouciance',
    'empirical',
    'perfunctory',
    'egregious',
    'lopsided',
    'feeble',
    'robust',
    'turbulent',
    'chronology',
    'synopsis',
    'awry',
    'astute',
    'defensive',
    'customary',
    'malady',
    'indiscretion',
    'prognosis',
    'variable',
    'antagonistic',
    'adversarial',
    'dichotomy',
    'untenable',
    'subvert',
    'enrich',
    'augment',
    'extend',
    'warble',
    'improvise',
    'shriek',
    'croon',
    'caterwaul'
];

var wordlist37 = [
    'epic',
    'mundane',
    'marvel',
    'exemplar',
    'glorify',
    'dilute',
    'antithesis',
    'lavish',
    'routine',
    'vacant',
    'homogeneous',
    'daunting',
    'durable',
    'demonstrate',
    'debunk',
    'authenticate',
    'predate',
    'vice',
    'compliment',
    'censure',
    'evident',
    'demanding',
    'sift',
    'achieve',
    'erode',
    'modify',
    'competence',
    'chaos',
    'disarray',
    'unruly',
    'uneven',
    'overarching',
    'mediocre',
    'somnolent',
    'slumber',
    'lethargic',
    'laconic',
    'befuddle',
    'evenhanded'
];

var wordlist38 = [
    'genuine',
    'resolution',
    'dilemma',
    'rigorous',
    'specious',
    'blatant',
    'unworldly',
    'ethos',
    'commonplace',
    'melancholy',
    'hamper',
    'trigger',
    'transcend',
    'fad',
    'empiricial',
    'utilitarian',
    'parochial',
    'quell',
    'conviction',
    'presage',
    'foster',
    'pertain',
    'mitigate',
    'unprecedented',
    'warrant',
    'novel',
    'exigent',
    'plot',
    'paradigm',
    'hodgepodge',
    'patchwork',
    'grant',
    'concession',
    'abnegate',
    'fractious',
    'affable',
    'sagacious',
    'easygoing'
];

var wordlist39 = [
    'zenith',
    'brute',
    'jar',
    'plausible',
    'conciliatory',
    'teem',
    'roil',
    'ebb',
    'empower',
    'overextend',
    'pseudonym',
    'remuneration',
    'replete',
    'hinder',
    'compulsory',
    'obligate',
    'emulate',
    'countermand',
    'mediate',
    'insipid',
    'conjure',
    'strip',
    'voluble',
    'heartfelt',
    'intelligible'
];

var wordlist40 = [
    'deterioration',
    'elicit',
    'evade',
    'discount',
    'subvert',
    'espouse',
    'exaggerate',
    'loath',
    'solitude',
    'obeisance',
    'frenzy',
    'emulate',
    'unprecedented',
    'perplex',
    'torpor',
    'arouse',
    'spew',
    'pitfall',
    'turbulent',
    'cynicism',
    'crude',
    'manifest',
    'mitigate',
    'undercut',
    'maze',
    'labyrinth',
    'intricate',
    'prevalent'
];

var wordlist41 = [
    'open-ended',
    'evocative',
    'polemical',
    'edify',
    'ambiguous',
    'misfeasance',
    'diffident',
    'meticulous',
    'implacable',
    'tenacious',
    'purport',
    'forbear ',
    'erratic',
    'erudite',
    'aesthetic',
    'pragmatic',
    'instinct',
    'acquired',
    'mundane',
    'undermine',
    'forgo',
    'literal',
    'honorific',
    'malign',
    'dispute',
    'diminutive',
    'minuscular',
    'omnipresent',
    'ethereal'
];

var wordlist42 = [
    'paralyze',
    'demoralize',
    'assuage',
    'exasperate',
    'encumber',
    'dilute',
    'circumvent',
    'naysayer',
    'pushover',
    'brag',
    'perplex',
    'absorbing',
    'erudite',
    'acrimony',
    'obligatory',
    'jettison',
    'contrive',
    'vacillate',
    'rebellious',
    'quirky',
    'flamboyant',
    'lucrative',
    'spurn',
    'comprehensive',
    'intelligible',
    'slippery',
    'elusive',
    'futile'
];

var wordlist43 = [
    'anomalous ',
    'haphazard ',
    'collective ',
    'monolithic',
    'melodramatic',
    'latent ',
    'mawkish',
    'austere',
    'ostentatious',
    'invaluable ',
    'exceptional',
    'inveterate',
    'routine',
    'conjecture',
    'wide-ranging ',
    'distinctive ',
    'debilitate ',
    'mimic ',
    'varnish',
    'labyrinthine',
    'entice',
    'gall',
    'placate',
    'rankle',
    'appease',
    'illuminate',
    'atypical',
    'insurmountable',
    'persevere',
    'improvise ',
    'evade ',
    'fungible',
    'durable',
    'connoisseur',
    'plethora',
    'surfeit',
    'amicable',
    'agreeable',
];

var wordlist44 = [
    'ample',
    'paucity',
    'impede',
    'incentive',
    'rationale',
    'transcend',
    'address',
    'mitigate',
    'mar',
    'compassionate',
    'decisive',
    'nepotism',
    'grandstand',
    'partisan',
    'vacillate',
    'synthesize',
    'uncanny',
    'apt',
    'supersede',
    'emergent',
    'discredit',
    'authoritative',
    'animate',
    'trendy',
    'impulsive',
    'stale',
    'spur',
    'foster',
    'verisimilitude',
    'sanguine',
    'cordial',
    'irascible',
    'convivial',
    'exasperate',
    'galvanize',
    'thwart'
];

var wordlist45 = [
    'barring',
    'eminent',
    'ridicule',
    'scrutinize',
    'embellish',
    'underrate',
    'inattentive',
    'delightful',
    'futile',
    'contagious',
    'propitious',
    'conspicuous',
    'equivocal',
    'contemplate',
    'alien',
    'lambast',
    'fret',
    'arduous',
    'trivial',
    'stagnate',
    'resonate',
    'outlandish',
    'consequential',
    'snag',
    'hitch',
    'upshot',
    'hallmark',
    'subscribe',
    'altruism',
    'fecund',
    'fertile',
    'transient'
];

var wordlist46 = [
    'anthropomorphize',
    'empathy',
    'recast',
    'fickie',
    'stalwart',
    'solicitous',
    'pretentious',
    'whismsy',
    'dispassionate',
    'incisive',
    'vitiate',
    'lionlize',
    'impugn',
    'warrant',
    'esoteric',
    'provisional',
    'hard-bolled',
    'query',
    'innocuous',
    'quizzical',
    'impertinent',
    'evasive',
    'elaborate',
    'gall',
    'feckless',
    'unwitting',
    'querulous',
    'pious',
    'preachy',
    'sanctimonious',
    'plaintive',
    'backwater',
    'covet',
    'arduous',
    'taxing',
    'preempt',
    'preface'
];

var wordlist47 = [
    'clamorous',
    'invidious',
    'numinous',
    'empirical',
    'sonorous',
    'imprint',
    'salutary',
    'deliberate',
    'sequential',
    'momentary',
    'inevitable',
    'testimony',
    'anecdote',
    'grant',
    'promise',
    'compromise',
    'disclose',
    'brook',
    'repudiate',
    'tonic',
    'overshadow',
    'preclude',
    'forge',
    'fractious',
    'purveyor',
    'hypercritic',
    'profit-monger',
    'inertial',
    'opprobrium',
    'platitude',
    'pugnacious',
    'truculent',
    'supercilious',
    'polarize',
    'conciliate',
    'astute',
    'nondescript',
    'intoxicate',
];

var wordlist48 = [
    'furtive',
    'archetypal',
    'incendiary',
    'ephemeral',
    'dazzle',
    'surreptitious',
    'resolve',
    'resent',
    'vexatious',
    'clandestine',
    'equitable',
    'strenuous',
    'validate',
    'collaborate',
    'spurn',
    'ponder',
    'litigant',
    'evidentiary',
    'exacerbate',
    'adduce',
    'obfuscate',
    'replicate',
    'intricate',
    'tedious',
    'canned',
    'convoluted',
    'vacuous',
    'tortuous',
    'formulaic',
    'hard-nosed',
    'engaging',
    'compassionate',
    'vigorous',
    'rehabilitate',
    'unerring'
];

var wordlist49 = [
    'plethora',
    'paucity',
    'upheaval',
    'demoralize',
    'negligible',
    'coax',
    'riveting',
    'traumatic',
    'souvenir',
    'retinue',
    'integrity',
    'foster',
    'decry',
    'tedious',
    'exclusive',
    'fickle',
    'wide-ranging',
    'experimental',
    'acclaim',
    'overarching',
    'meld',
    'spearhead',
    'pacific',
    'lethargic',
    'austere',
    'dovish',
    'acrimony'
];

var wordlist50 = [
    'predilection',
    'invective',
    'tenacious',
    'pugnacious',
    'effusive',
    'merge',
    'equable',
    'tremendous',
    'extraneous',
    'render',
    'scatter',
    'plummet',
    'disperse',
    'displace',
    'ostensible',
    'antithesis',
    'concise',
    'sensational',
    'immense',
    'consummate',
    'oracle',
    'prophetic',
    'inexplicable',
    'inauspicious',
    'divert',
    'annihilate',
    'watershed',
    'ameliorate',
    'exacerbate',
    'extenuate',
];

var wordlist51 = [
    'quixotic',
    'prescience',
    'viable',
    'impassive',
    'solitary',
    'sluggish',
    'draconian',
    'rapacious',
    'deplete',
    'hidebound',
    'embolden',
    'encumber',
    'conversant',
    'purport',
    'arcane',
    'midst',
    'chaos',
    'self-defeating',
    'aggrandize',
    'perpetuate',
    'abuse',
    'archaic',
    'misuse',
    'untenable',
    'cliche',
    'condescend',
    'outright',
    'malfeasance',
    'fraudulent',
    'hysteria',
    'vilify',
    'stymie',
    'aggrieve'
];

var wordlist52 = [
    'preempt',
    'pretentious',
    'vitiate',
    'sanctimonious',
    'impugn',
    'disclose',
    'invidious',
    'platitude',
    'brook',
    'coax',
    'opprobrium',
    'fractious',
    'litigant',
    'incendiary',
    'tedious',
    'unerring',
    'vexatious',
    'traumatic'
];

var wordlist53 = [
    'proliferate',
    'cataclysm',
    'pervasive',
    'deride',
    'sacrosanct',
    'ephemeral',
    'malleable',
    'egalitarian',
    'autonomous',
    'contiguous',
    'endanger',
    'anthropogenic',
    'mutual',
    'salient',
    'robust',
    'evanescent',
    'cumbersome',
    'unwieldy',
    'eccentric',
    'predilection',
    'vacillate',
    'waver',
    'cowardice',
    'reinforce',
    'inverse',
    'unfeeling',
    'benign',
    'orthodox',
    'anomalous',
    'embody',
    'repertoire',
    'context',
    'straightforward',
    'augment',
    'ameliorate',
    'extrovert',
    'essential',
    'indispensable',
    'conscientious',
];

var wordlist54 = [
    'tantamount',
    'vindicate',
    'proscribe',
    'valediction',
    'exculpate',
    'affable',
    'ebullient',
    'irascible',
    'overwrought',
    'measured',
    'chronology',
    'synopsis',
    'awry',
    'astute',
    'discount',
    'emulate',
    'commend',
    'egalitarian',
    'anachronism',
    'regal',
    'forbear',
    'impetuous',
    'boorish',
    'chivalrous',
    'circumspect',
    'cease',
    'encyclopedic',
    'long-winded',
    'rambling',
    'overbearing',
    'high-minded',
    'allege',
    'unimpeachable',
    'ingenious',
    'unassuming',
    'seditious',
];

var wordlist55 = [
    'concur',
    'erudite',
    'contentious',
    'methodical',
    'experimental',
    'formulaic',
    'lucrative',
    'extrapolate',
    'resemble',
    'drawback',
    'discredit',
    'de-emphasize',
    'check',
    'doom',
    'surfeit',
    'conundrum',
    'forestall',
    'forgo',
    'endemic',
    'dominant',
    'elaborate',
    'utilitarian',
    'poise',
    'wane',
    'ebb',
    'noteworthy',
    'generosity',
    'integrity',
    'eloquent'
];

var wordlist56 = [
    'ignorant',
    'decry',
    'boast',
    'downplay',
    'unbounded',
    'disseminate',
    'magnificent',
    'molder',
    'warehouse',
    'triumph',
    'diffuse',
    'irk',
    'immerse',
    'asset',
    'flippant',
    'tendentious',
    'languish',
    'proliferate',
    'jettison',
    'thrive',
    'dilemma',
    'quandary',
    'ploy',
    'spike',
    'upsurge',
    'harbinger',
    'lull',
    'portent',
    'respite',
    'gratify',
    'entice',
    'cantankerous',
    'betray'
];

var wordlist57 = [
    'embrace',
    'hyperbole',
    'trickster',
    'disdain',
    'relish',
    'notwithstanding',
    'genteel',
    'impassioned',
    'upheaval',
    'imminent',
    'stern',
    'prescience',
    'prophetic',
    'fiery',
    'winnow ',
    'oppressive ',
    'quash',
    'temptation',
    'nascent ',
    'dearth',
    'unambiguous',
    'transcend',
    'averse',
    'parochial',
];

var wordlist58 = [
    'deduce',
    'explicable',
    'formidable',
    'specious',
    'irreversible',
    'frown',
    'rampant',
    'detriment',
    'flip',
    'infinite',
    'skirt',
    'scrutinize',
    'repudiate',
    'confound',
    'confine',
    'counterfeit',
    'overstate',
    'counterintuitive',
    'replete',
    'encomium',
    'indict',
    'exalt',
    'rehabilitate',
    'excoriate',
    'valorize',
];

var wordlist59 = [
    'tenacious',
    'diffident',
    'meticulous',
    'implacable',
    'gossamer',
    'contrive',
    'mascot',
    'flit',
    'archaic',
    'neutralize',
    'paradigm',
    'tilt',
    'tweak',
    'controvert',
    'articulate',
    'entrench',
    'bolster',
    'deviate',
    'succumb',
    'recoil',
    'pious',
    'preachy',
    'querulous',
    'encompass',
    'sanctimonious',
    'plaintive',
    'ubiquitous',
    'refine',
    'omnipresent'
];

var wordlist60 = [
    'numerous',
    'fury',
    'usage',
    'severe',
    'sober',
    'dejected',
    'belie',
    'conflate',
    'divulge',
    'fictitious',
    'hallmark',
    'eloquent',
    'marvel',
    'meticulous',
    'rebellious',
    'quirky',
    'flamboyant',
    'cast-iron',
    'reproach',
    'respite',
    'edify',
    'discreet',
    'precipitate',
    'tactful',
    'forbear',
    'conspire',
    'rampant',
    'ensue',
    'hearten',
    'atypical',
    'concomitant',
    'elusive',
    'sloth',
    'gleam',
    'imperial',
    'paraphernalia',
    'august',
    'majestic'
];

var wordlist61 = [
    'detritus',
    'extraneous',
    'rivalry',
    'cluster',
    'oblivious',
    'prominence',
    'undermine',
    'empower',
    'surrender',
    'glean',
    'supersede',
    'halt',
    'disparate',
    'feedback',
    'static',
    'perpetuate',
    'ephemeral',
    'perilous',
    'undue',
    'scant',
    'dwindle',
    'concrete',
    'finite',
    'meager',
    'conclusive',
    'elucidate',
    'obfuscate',
];

var wordlist62 = [
    'self-serving',
    'belie',
    'conflate',
    'divulge',
    'naive',
    'premeditate',
    'manipulate',
    'testimony',
    'anecdote',
    'predominant',
    'arguably',
    'influential',
    'lengthy',
    'bibliography',
    'elude',
    'cast-iron',
    'reproach',
    'respite',
    'exacting',
    'onerous',
    'rebellious',
    'quirky',
    'flamboyant',
    'condemn',
    'rant',
    'diatribe',
    'exculpate',
    'disquisition',
    'vindicate'
];

var wordlist63 = [
    'harrow',
    'convoluted',
    'implausible',
    'avant-garde',
    'flout',
    'cultivate',
    'sensational',
    'de-emphasize',
    'check',
    'doom',
    'bypass',
    'conspire',
    'rampant',
    'ensue',
    'hearten',
    'atypical',
    'concomitant',
    'compromise',
    'proclaim',
    'profess',
    'disown',
    'betray',
    'provocative',
    'confine',
    'exhilarate',
    'antagonize',
    'contentious',
    'pedestrian',
    'perplex',
    'mundane',
    'intriguing',
    'compliment',
    'backhanded',
    'paltry',
    'heartfelt',
    'meager'
];

var wordlist64 = [
    'zenith',
    'brute',
    'jar',
    'plausible',
    'conciliatory',
    'truism',
    'valediction',
    'resolve',
    'gainsay',
    'downplay',
    'esoteric',
    'arcane',
    'comprehensive',
    'provocative',
    'stipulate',
    'disseminate',
    'ponderous',
    'empirical',
    'laudatory',
    'deify',
    'debunk',
    'aggrandize',
    'implacable',
    'unyielding',
    'impeccable',
    'unqualified',
    'capricious',
    'antediluvian',
    'flighty',
    'archaic',
    'chauvinistic',
    'patronize',
    'delude',
    'hitherto'
];

var wordlist65 = [
    'yield',
    'anomalous',
    'enigmatic',
    'surreptitious',
    'resolve',
    'resent',
    'vexatious',
    'clandestine',
    'equitable',
    'dispense',
    'inflate',
    'fastidious',
    'overblow',
    'improvise',
    'countermand',
    'commensurate',
    'parity',
    'inclusive',
    'stratify',
    'venue',
    'seclusion',
    'opulent',
    'enormous',
    'sycophantic',
    'ascetic',
    'mercenary',
    'allusion',
    'ramification',
    'respite',
    'beguile',
    'baffle',
    'buoy',
    'insouciance',
    'stoicism',
    'alacrity',
    'cordial',
    'convivial',
    'overshadow',
    'leach',
    'ubiquitous',
    'brackish',
    'malodorous',
    'redolent',
    'noisome',
    'anodyne',
];

var resultList1 = [
    'n. 摩擦；磨损；消耗',
    'vt. 使变形；使变质',
    'n. 霸权；领导权；盟主权',
    'adj. 难懂的；易忘的；逃避的；难捉摸的',
    'adj. 容易消散的；逐渐消失的；会凋零的',
    'vt. 使烦恼；使厌倦',
    'adj. 坚定的；不变的',
    'n. 再发作，复发',
    'n. 不诚实；背信弃义',
    'adj. 怀恨的；有报仇心的；惩罚的',
    'n. 底线，[计] 下划线',
    'n. 冰雹；致敬；招呼；一阵',
    'adj. 适当的；贴切的',
    'n. 直路',
    'adj. 虔诚的；恭敬的；尊敬的',
    'adj. 深奥的；难懂的',
    'n. 昏睡；死气沉沉；嗜眠（症）',
    'adj. 无趣味的；无生气的；索然乏味的',
    'n. 反责，反控；揭丑',
    'vt. 恳求，哀求；恳请',
    'n. 坚定分子',
    'n. 偶像破坏者；提倡打破旧习的人',
    'n. 拜占庭人，拜占庭派的建筑师',
    'adj. 久坐的；坐惯的；定栖的；静坐的',
    'adj. 不可侵犯的；神圣的；不可亵渎的',
    'vt. 避免，防止；转移',
    'adj. 陈腐的；平庸的；老一套的',
    'adj. 实际的；实用主义的；国事的',
    'adj. 冷静的；泰然自若的',
    'n. 先例；前例',
    'adj. 昏暗的，朦胧的；晦涩的，不清楚的；隐蔽的；不著名的，无名的',
    'n. 巨头；大资本家；要人；富豪；……大王',
    'vt. 先占；先取；以先买权获得',
    'n. 血红色',
    'n. 恶言漫骂',
    'adj. 恶臭的；有害的',
    'adj. 空的；空虚的；空洞的；无意义的',
    'vt. 转移；移交；使滚下；衰落',
    'adj. 透明的；清晰的；明了的',
    'adj. 贫困的；贫穷的（副词indigently）',
    'adj. 错误的；扭曲的',
    'adj. 神秘的；离奇的；可怕的',
    'adj. 轻蔑的；侮辱的',
    'vt. 使惊呆；使昏迷',
    'vt. 例证；例示',
    'adj. 无畏的；鲁莽的',
    'adj. 无理由的，无端的；免费的',
    'n. 标志；旗子',
    'vt. 代替；排挤掉',
    'n. 副本；复制品',
    'adj. 浑浊的；混乱的；雾重的',
    'adj. 适合的；吉利的；顺利的',
    'adj. 受折磨的；撕碎的',
    'adj. 不受影响的，无动于衷的；不能渗透的',
    'adj. 给人好感的；有魅力的；引人注意的',
    'vt. 合并；异文合并',
    'vt. 引起，唤起；博得',
    'n. 贪婪，贪财',
    'adj. 轻率的，鲁莽的；不小心的',
    'vt. 制止，阻止；使打消念头',
    'adj. 华丽的；装饰的；（文体）绚丽的',
    'adj. 臭的；恶臭的；腐臭的',
    'vt. 严惩；苛评；矫正；修订',
    'n. 束缚；羁绊；脚镣',
    'adj. 有密切关系的；贴切的；恰当的',
    'adj. 自夸的；大肆吹嘘的',
    'n. 挥霍无度的人；浪费的人',
    'adj. 丰富的；很多的；慷慨的；浪费的',
    'n. 范例；词形变化表',
    'n. 缺乏；少数；少量',
    'vt. 使困惑，使为难；使复杂化',
    'vt. 承认；公开宣称；坦率承认',
    'adj. 恶毒的；有恶意的；坏心肠的',
    'n. 偶像崇拜；盲目崇拜；邪神崇拜',
    'vt. 煽动，教唆；支持',
    'n. 叩头',
    'adj. 故意的；深思熟虑的；从容的',
    'vt. 分配；拨出；使坐落于',
    'adj. 慷慨的；大方的；无限制的',
    'n. 刺激；（赶牲口用的）刺棒；激励'
];

var resultList2 = [
    'adj, 自治的',
    'n. 弱点；小缺点；癖好',
    'adj. 懒惰的；无痛的',
    'adj. 透明的；平静的，无忧虑的',
    'adj. 刻苦的，勤勉的',
    'vt. 放弃；撤回',
    'vt. 使结束；使达到高潮',
    'n. 倾斜物',
    'adj. 恭敬的；惯于顺从的',
    'n. 弊病；疾病；腐败',
    'n. 误传，谬传；谣言',
    'n. 贪心，贪婪',
    'vt. 吸收；使同化；把…比作；使相似',
    'vt. 使失去勇气；使身心交疲；使焦躁；使失常',
    'n. 敏捷；轻快；乐意',
    'adj. 社交的；群居的',
    'vt. 解释；详细说明',
    'n. 收缩核',
    'adj. 热心的，热情的，积极的',
    'adj. 吵闹的，喧嚣的；难驾驭的',
    'n. 多年生植物',
    'vt. 绘制；延长；伸展',
    'n. 责难',
    'n. 精髓；核心；骨髓；要旨',
    'adj. 有暴风雨的；暴乱的；剧烈的',
    'adj. 好奇的；好问的，爱打听的',
    'n. 分遣队；偶然事件；分得部分；代表团',
    'adj. 原始的，古时的；纯朴的',
    'n. 挽歌；恸哭；悲痛之情',
    'n. 同时代的人',
    'adj. 贪婪的；贪吃的；狼吞虎咽的',
    'vt. 平息，缓和；使…平静；使…变软',
    'adj. 好辩的；好争论的；挑起论战的',
    'vi. 加入；同意；就任',
    'adj. 异端的；异教的',
    'vt. 支持；嫁娶；赞成；信奉',
    'n. 困惑；窘境；为难',
    'adj. 易于管教的；易驾驭的；易处理的；驯良的',
    'adj. 古怪的；异想天开的；反复无常的',
    'adj. 同等的；相当于…的',
    'n. [心理] 自恋，自我陶醉',
    'n. (Banal)人名；(法、意)巴纳尔',
    'vt. 排除；避免；消除',
    'adj. 节俭的；朴素的；花钱少的',
    'n. 平静；镇定',
    'n. 奶牛，母牛；母兽',
    'n. 成分；选民；委托人',
    'n. 牧师礼服',
    'vt. 根除，根绝；消灭',
    'n. 圣人；贤人；哲人',
    'n. [物化] 催化剂；刺激因素',
    'adj. 千变万化的；一人演几个角色的；变形虫的',
    'vt. 责难，谴责；诽谤',
    'vt. 减轻；低估；为…找借口；使人原谅',
    'vt. 控告，起诉；[法] 揭发',
    'prep. 无；缺',
    'adj. 逃避的；托辞的；推托的',
    'adj. 羞怯的；缺乏自信的；谦虚谨慎的',
    'adj. 厌倦的；疲倦不堪的',
    'vt. 减轻；掩饰；辩解',
    'adj. 狡猾的；淘气的；诡密的',
    'n. 理解；恐惧；逮捕；忧惧',
    'n. 无数，极大数量；无数的人或物',
    'adj. 宽敞的；方便的',
    'adj. 易怒的；倔强的，难以对待的',
    'adj. 杂色的；斑驳的；富于变化的',
    'n. 卑鄙；奸恶',
    'adj. 零星的；分散的；不定时发生的',
    'vt. 合并；使（金属）汞齐化；混合',
    'n. 精密；美好；细节；拘泥细节',
    'adj. 初期的；开始存在的，发生中的',
    'n. 遗赠，遗产',
    'n. 无法相比的东西',
    'n. 拙劣的模仿；诙谐的改编诗文',
    'vt. 平息；缓和；减轻',
    'n. 放荡者；享乐者',
    'adj. 微妙的；精细的；敏感的；狡猾的；稀薄的',
    'vt. 破坏，渐渐破坏；挖掘地基',
    'n. 敬礼；尊敬',
    'adj. 无私的；公正的；冷漠的；廉洁的'
];

var resultList3 = [
    '基本的，基本构成物的<br/>重要的，必要的',
    '坚定的信仰，信念',
    '(自然)倾向；能力',
    '反感，厌恶',
    '无知',
    '鄙视，蔑视',
    '喜欢冒险的',
    '轻浮的<br/>毫无价值的，微不足道的',
    '固执任性的',
    '不合逻辑的',
    '易受攻击的<br/>脆弱的，易受伤害的',
    '认为，认定',
    '怀疑他人动机不纯的',
    '客观公正的',
    '结果，后果',
    '削弱',
    '使分心<br/>使高兴',
    '弥补，改善<br/>赎回，买回',
    '保存，保留',
    '阻止，先发制人<br/>抢占',
    '可以计量的',
    '用不完的，无穷无尽的',
    '值得注意的，不同寻常的',
    '资助人，捐助人',
    '先例；前例',
    '替代物',
    '好心的，出于好意的',
    '放心的',
    '拘留',
];

var resultList4 = [
    '矛盾',
    '占主导地位的，主要的',
    '安静的',
    '平静的',
    '使焦虑，使不安',
    '全面的',
    '贬损，诋毁',
    '友善的',
    '茂视，鄙视',
    '(因地位髙或年长而） 尊敬',
    '孤立的<br/>思想狭隘,守旧的',
    '概要的',
    '极好的<br/>(通过可怕的细节)令 人兴奋的，骇人听闻',
    '不寻常的<br/>杰出的，超常的',
    '过渡的',
    '使分离，使隔离',
    '超出，超过<br/>遮盖',
    '全等的，一致的',
    '矛盾的事物',
    '相互作用，互惠',
    '次要的<br/>顺从的，服从的',
    '辅助，帮助',
    '避免，防止',
    '抑制',
    '使窘迫，使为难',
    '苛刻的，刻薄的',
    '羞辱，使丢脸',
    '使为难，使不安',
    '迷惑，欺骗',
    '使......对所企求的东西,可望而不可及',
    '剥夺，迫使放弃',
    '帝王的，王室的',
    '丧失，被没收',
    '降低，使贬值'
];

var resultList5 = [
    '无聊',
    '异教的，异端的',
    '修饰，润色',
    '固执的',
    '轻信',
    '美味的<br/>称心如意的',
    '显眼的，明显的',
    '贮藏',
    '践踏',
    '找回，重新获得',
    '基础的',
    '冒昧的',
    '红利',
    '多年生的（植物）<br/>持续的，长期的',
    '典型',
    '挑刺的，吹毛求疵的',
    '恐吓，使畏惧',
    '镇静，平衡',
    '安协，让步',
    '阻止',
    '严厉的，严格的',
    '抗议',
];

var resultList6 = [
    '超自然的',
    '阐释，阐明',
    '朴实的，单纯的',
    '真实的，准确的',
    '突发奇想',
    '神',
    '为......报仇',
    '厌倦的<br/>疲倦的',
    '纯朴的，真诚的',
    '关心的',
    '有报仇心的，报复性的',
    '客观的',
    '不足的，少的',
    '相等的，相似的',
    '证明',
    '限制',
    '脱离世俗的',
    '(团体的）气质，氛 围，信仰等',
    '香味',
    '使......有权利',
    '使丧失，剝夺',
    '共谋，协力',
    '集体的，共同的',
    '离散的，不连续的',
    '(依据已知信息）推测',
    '抄写',
    '详细阐述<br/>夸大',
    '滑稽的',
    '报警器',
    '驱散，消除',
    '留意的，注意的',
    '好奇的',
    '善于接受的',
    '显著区别的'
];

var resultList7 = [
    '(一段）时间',
    '大量',
    '暂停，中止',
    '交换<br/>往复运动',
    '使丧失信誉',
    '大量的',
    '共同的，联合的',
    '修改',
    '处理',
    '符合，遵守',
    '恶毒的',
    '复杂的',
    '实体',
    '难懂的，复杂的',
    '无固定形状的',
    '虚假的',
    '强烈渴望',
    '沉思的，冥想的',
    '不热情的，冷淡的',
    '开始',
    '变弱，变君弱<br/>踌躇，犹豫',
    '减少，下降',
    '抑制，使扫兴',
];

var resultList8 = [
    '占主导地位',
    '易受影响的',
    '幼稚的',
    '固执的',
    '果断的',
    '天才的，有独创性的',
    '坚决',
    '难懂的',
    '突发奇想',
    '引起，引发',
    '引起，引发<br/>激怒',
    '催化剂',
    '隐藏，伪装',
    '阻碍',
    '完满的，圆满的',
    '加速<br/>鲁莽的',
    '全面的',
    '发现，注意',
    '可证实的',
    '明显的，显眼的',
    '过时的'
];

var resultList9 = [
    '反思的，沉思的',
    '使喜爱',
    '精美的，精致的',
    '综合物',
    '事先考察',
    '松弛的',
    '不可靠的，背叛的',
    '受到尊敬的',
    '久坐的',
    '分销',
    '挽救',
    '获得',
    '优势，支配地位',
    '(严重地）破坏',
    '攻击，贬损',
    '复兴',
    '图谋，谋取',
    '使...复苏',
    '浮现，涌现',
    '衰弱',
    '吸引人的',
    '共谋',
    '低估',
    '超自然的',
    '憎恨，怨恨',
    '争辩',
    '夸大，吹捧<br/>抬髙身价，提髙地位',
    '装饰',
    '使...危险'
];

var resultList10 = [
    '专制的',
    '模棱两可的，有歧义的',
    '嗜食同类',
    '搜索',
    '捕食',
    '宽容的，允许的',
    '明确的，清楚的',
    '话多的',
    '严厉的责难',
    '夸大的言辞',
    '委婉的表达',
    '过时的',
    '经常的<br/>稳定的，不变的',
    '典型',
    '奇怪的，难以想象的',
    '古怪的',
    '礼貌的',
    '粗糙的<br/>粗鲁的',
    '派别，小集团',
    '统一的，相同的',
    '壮观的',
    '磨蹭<br/>缓慢消失',
];

var resultList11 = [
    '简述，概述',
    '鲁莽的，仓促的',
    '讽刺，挖苦',
    '嘲弄',
    '轻视，蔑视',
    '自以为髙人一等，傲慢 态度',
    '标新立异之人<br/>特立独行的',
    '权威的，可信的',
    '清楚有力地表达',
    '重复强调',
    '殷勤，彬彬有礼',
    '勇敢，勇敢的行为',
    '辛辣的，刺激的<br/>令人痛苦的',
    '哀伤的，悲哀的',
    '值得赞美的',
    '胆小的，怯懦的',
    '独特的气质',
    '前驱',
    '兼容的，能共存的'
];

var resultList12 = [
    '临时的，暂时的',
    '至今',
    '僵化',
    '违法行为，不道德行为',
    '强制，迫使',
    '恐吓，威胁',
    '无忧无虑的<br/>快乐的',
    '孵化，培养',
    '国内的<br/>家庭的',
    '无光泽的，平凡的',
    '虚弱的，无能的<br/>粗心的，不负责任的',
    '讽刺漫画',
    '拯救，救助',
    '返祖现象',
    '偏离，误差',
    '化身',
    '赞美',
    '变形，变化',
    '习惯于（不好的事物）',
    '冷漠的，无动于衷的<br/>面无表情的',
    '憎恨，生气',
    '理解',
    '恐怖的，可怕的<br/>令人惊叹的',
    '凶猛，残忍',
    '逆境，不幸',
    '使...恶化',
    '根除',
    '改善，提升',
    '寓言',
    '举例说明'
];

var resultList13 = [
    '谨慎的',
    '勉强的，不情愿的',
    '使困惑',
    '谄媚的',
    '不妥协的，固执的',
    '(因地位高或年长而） 尊敬',
    '疏忽大意的',
    '道德的',
    '供选择的',
    '了不起的',
    '有效率的',
    '精湛的技艺',
    '民主的',
    '狭隘的',
    '革命性的',
    '有限的',
    '努力的',
    '保持',
    '不友好的，敌对的',
    '辱骂，斥责',
    '详细检查',
    '疏忽，忽视',
    '分裂',
    '报酬',
    '复杂',
    '无用的',
    '(思想）堕落的，颓废 的<br/>三俗的(庸俗、低俗、 媚俗的）'
];

var resultList14 = [
    '确定，证实',
    '句法的，语法的',
    '经济的，简练的',
    '改变',
    '抗议',
    '引人注意的,酷炫的',
    '单调的，沉闷的',
    '肮脏的<br/>卑鄙的',
    '粗鲁的，无礼貌的',
    '亲戚，同族',
    '合并',
    '等级制度，有等级划 分的组织<br/>权力机构',
    '预感',
    '演绎，推论',
    '宏伟的',
    '阻止',
    '驱逐<br/>取代，代替',
    '显然的，明显的<br/>清晰地展示，显露出',
    '看起来合理的',
    '基本的',
    '使和解，使一致',
    '(语言）辛辣尖刻的',
    '繁重的，费力的',
    '勉强的，不情愿的'
];



var resultList15 = [
    '获得；实现',
    '确定的',
    '严格的<br/>细致的，准确的',
    '矫正方法',
    '阻止',
    '相对应的人或物',
    '门徒，信徒',
    '沉默寡言<br/>保留',
    '缺乏自信的',
    '引起争议的<br/>爱争吵的',
    '爱开玩笑的',
    '冒昧的',
    '无畏的',
    '党派的，排他的',
    '安静的',
    '蔓延',
    '证明......是错误的',
    '拒绝，否定',
    '宽恕，原i宁、',
    '抚慰，使和解',
    '模仿',
    '地点，中心',
    '平凡的，无聊的',
    '批评，攻击',
    '使...喜悦或兴奋',
    '制服，击溃',
    '设计，谋划',
    '多产的'
];

var resultList16 = [
    '广泛的，大量的',
    '草料，饲料',
    '撤退',
    '有序的',
    '正直',
    '传输，传递',
    '操控',
    '夸大，吹捧<br/>抬髙身价，提髙地位',
    '难懂的，只有少数人懂 得的',
    '清楚的，明确的',
    '毋庸置疑的',
    '不遵守<br/>违抗',
    '影响',
    '一贯的<br/>习惯做....的',
    '私有的',
    '嘲笑，耻笑',
    '使敌对，使对抗',
    '专制的，独裁的',
    '少量',
    '持不同意见',
    '提出不同意见',
    '分裂',
    '迎合，满足需求',
    '茂视，鄙视',
    '逃跑，逃避<br/>使...无法理解'
];

var resultList17 = [
    '不可缺少的',
    '离散的，不连续的',
    '卓越的',
    '相关的',
    '暗讽，讽刺',
    '侮辱，辱骂',
    '说话过于直白的<br/>反映迟钝的<br/>不锋利的',
    '暄闹的',
    '谬误的',
    '装饰',
    '阻止',
    '开始，启动',
    '抑制，阻止',
    '回避的，闪烁其词的',
    '直率的',
    '典范',
    '误称',
    '深刻的<br/>强烈的',
    '异常，异常事物',
    '疏远<br/>使...变得不友好',
    '使敌对，使对抗',
    '恐吓，威胁',
    '平息，缓和',
    '促进，激起',
    '巧合的；_致的',
    '讽刺的',
    '沮丧',
    '鄙视'
];

var resultList18 = [
    '与...相似',
    '责难',
    '称赞，赞同',
    '阐释，阐明',
    '免除',
    '难以处理的',
    '使...惊讶',
    '验证，证明....是真实的',
    '灌输',
    '修改，修正',
    '传播，散布',
    '轻描淡写，低估',
    '赞美',
    '杂乱无章的',
    '享乐主义',
    '缺乏的，不足的',
    '密谋，诡计<br/>引起',
    '垂涎',
    '憎恨，生气'
];

var resultList19 = [
    '忧郁的',
    '变弱，变君弱<br/>踌躇，犹豫',
    '易......的<br/>有责任的，有义务的',
    '使...进入某种状态',
    '武断的，任性的<br/>随意的',
    '多余的',
    '实际的',
    '喜欢冒险的',
    '根据观察或经验的',
    '看起来合理的',
    '宏伟壮观的',
    '口头语的，俗语的',
    '仔细分析',
    '不予考虑',
    '即兴表演',
    '顶点，最髙潮',
    '尊敬',
    '迅速成长',
    '厌恶人类，厌世',
    '镇定',
    '挥霍的',
    '精力充沛的',
    '掩饰<br/>证明......虚假错误',
    '使...恶化'
];

var resultList20 = [
    '值得赞美的',
    '真实的，准确的',
    '无用的',
    '内省，自省',
    '过量的<br/>热情洋溢的',
    '独特的气质',
    '多产的',
    '久坐的',
    '迟钝的',
    '故意的，刻意的',
    '不服管理的',
    '精心的，精细的',
    '识别，察觉',
    '边缘的，不重要的',
    '邻近的',
    '相似的',
    '天才的，聪明的',
    '策略，诡计',
    '设计，谋划',
    '克制，忍耐',
    '引起争议的，引起分裂 的',
    '诱人的',
    '限定',
    '无序的，凌乱的',
    '短暂的',
    '过时的',
    '古怪的',
    '推迟<br/>顺从',
    '授予，给予<br/>协商',
    '赞美',
    '蔑视，鄙视'
];

var resultList21 = [
    '征税',
    '通行费',
    '改善，提升',
    '意见_致',
    '有正确判断力的',
    '一针见血的，深刻尖锐 的',
    '对立',
    '投降，放弃',
    '无政府状态；混乱',
    '专横，残暴',
    '自治',
    '虚假的',
    '难懂的',
    '字面的，不夸张的',
    '潜藏的，潜在的',
    '暗指',
    '公理的；不言自明的',
    '不吉利的',
    '尖酸刻薄的',
    '不一致的'
];

var resultList22 = [
    '过渡',
    '强制的，命令的',
    '证实',
    '毁灭，消灭',
    '引用...证明',
    '承认',
    '不知情的，无意识的',
    '替代的，代理的',
    '无序的，凌乱的',
    '使平衡，抵消',
    '亵渎',
    '难驾驭的，难处理的',
    '不容质疑的',
    '平衡',
    '犹豫不决',
    '粗心的，不留意的',
    '遥远的'
];

var resultList23 = [
    '妙语，俏皮话',
    '生动有趣的，机智幽默 的',
    '清晰明了的，易懂的',
    '使显得愚笨',
    '爱开玩笑的',
    '危险的',
    '轻蔑的（话语）',
    '无固定形状的',
    '排除',
    '即将发生的',
    '仔细检查',
    '嘲笑，嘲弄',
    '信仰虔诚的<br/>虚伪的',
    '分散，转移（注意力， 精神）<br/>通过转移注意力使人愉 悦',
    '突发奇想',
    '受帮助的人',
    '无趣，无聊',
    '(引起混乱的）巨变',
    '安静的',
    '累赘<br/>责任，义务',
    '矫揉造作，过分讲究',
    '滑稽，滑稽表演',
    '样板戏，情节夸张的戏 剧',
];

var resultList24 = [
    '单调的',
    '实际上的<br/>虚的，内心的',
    '私有的',
    '必要的',
    '留心，注意',
    '原谅，认可',
    '反传统的，反崇拜的',
    '粗心的，鲁莽的',
    '专横的，傲慢的',
    '后悔的，忏悔的',
    '啰嗦',
    '鲁莽的，仓促的',
    '沉默寡言的',
    '透明的<br/>清晰易懂的',
    '性格多变的',
    '偏袒的',
    '普通寻常的',
    '古怪的',
    '虚假的',
    '前兆<br/>预兆',
    '预言的',
    '开始',
    '拨款，挪用',
    '不停的，连续的',
    '描绘轮廓<br/>详细描述',
    '妥协<br/>损害',
    '机智，精明',
    '煞费苦心地做',
    '尊敬',
    '小心谨慎的，挑剔的',
    '用于教育他人的',
    '掩饰<br/>证明...虛假错误<br/>与...不符',
    '超出，超过<br/>遮盖',
    '无情的，苛求的<br/>不节检的',
    '限制',
    '不重要的',
    '主张<br/>断言'
];

var resultList25 = [
    '调和',
    '即兴表演',
    '公幵支持',
    '吵闹',
    '和谐，一致',
    '困境',
    '恶化',
    '曲解',
    '激励',
    '假的，伪造的',
    '过时的',
    '一致的，适合的',
    '偶然的',
    '怀疑他人动机不纯的',
    '想象出',
    '垂涎，觊觎',
    '使...恶化',
    '授权，认可',
    '全面的',
    '精练的，简洁有力的',
    '认为，视作',
    '产生<br/>屈服',
    '仔细检查',
    '变化多端的',
    '佐证，提供证据证明',
    '拆穿，揭露...的错误',
    '新手',
    '复杂的',
    '相当的，重要的',
    '平等的，公平的',
    '偶然的<br/>幸运的',
    '耸肩',
    '改善，提升',
    '查明'
];

var resultList26 = [
    '回避的，闪烁其词的',
    '误称',
    '异常，反常',
    '难以察觉的',
    '无情的',
    '易受影响的',
    '使...进入某种状态',
    '令人昏昏欲睡的',
    '清晰的',
    '口头的，非正式的',
    '卖弄知识的',
    '传播，散布',
    '费力的，苛求的',
    '尖酸刻薄的',
    '节检',
    '吝啬的<br/>不足的',
    '节检',
    '疏远<br/>背叛',
    '紊乱',
    '恶化',
    '在...之中',
    '直率的',
    '典范',
    '深刻',
    '处境危险的',
    '(论点）经不起反驳 的，站不住脚的',
    '有趣的<br/>有说服力的',
    '赞美的<br/>免费的',
    '严厉的批评<br/>平底锅',
    '冗长无聊的',
    '举止<br/>关系',
    '苛刻的<br/>艰巨的',
    '大量的',
    '吝啬的',
    '破坏，颠覆',
    '使疏远'
];

var resultList27 = [
    '精神抖擞的',
    '进取心',
    '消除',
    '多变性',
    '肮脏的',
    '辛辣尖刻的',
    '预感',
    '消除',
    '注解，标志',
    '暗喻',
    '内含',
    '推测',
    '明智地',
    '奇迹',
    '隐蔽的',
    '使钝化',
    '英勇的',
    '重复的',
    '同情',
    '谨慎的',
    '迫近的',
    '关怀',
    '同情心',
    '平稳的，合情合理的',
];

var resultList28 = [
    '肤浅的',
    '哗众取宠，大肆宣传',
    '机智幽默的评论',
    '悲伤的思考的',
    '古怪的，搞笑的',
    '禁欲主义，坚忍',
    '小心谨慎的',
    '友善的',
    '状态良好的<br/>明智的，合理的',
    '非常有趣的',
    '追溯的，有追溯效力的',
    '变会缓慢',
    '抑制',
    '障碍物，负担',
    '万灵药',
    '瓦解，崩塌',
    '兜售，大力吹捧',
    '薄弱的，站不住脚的',
    '使合理',
    '放大',
    '吐露',
    '质量的',
    '多余，过量',
    '避免，阻止',
    '阻止',
    '主寺会卖<br/>忍受',
    '预测，预言',
    '预示',
    '秘密的，隐蔽的',
    '危险的',
    '秘密的，隐蔽的',
    '使喜悦或兴奋',
    '基本的',
    '组成多样的，混合的'
];

var resultList29 = [
    '性格多变的',
    '迟钝的，冷漠的',
    '漠不关心的',
    '狡猾机智的<br/>技艺高超的',
    '快乐的，无忧无虑 的',
    '独裁的',
    '做作的，不自然的',
    '夸大狂',
    '平等的',
    '懒惰的',
    '有魅力的',
    '预测，预后',
    '吉祥的',
    '兜圈子的，不直接 的',
    '全面的',
    '即兴的<br/>自主的，自发的<br/>自然的，不刻意的',
    '油嘴滑舌的',
    '真实的，准确的',
    '活力四射的',
    '伪造<br/>锻造',
    '摒弃，蔑视',
    '小团体',
    '聚集',
    '惰性的，不活跃的',
    '欢乐的，喜悦的',
    '引起快感的',
    '使...衰弱',
    '强调',
    '绕过，回避',
    '新手',
    '新手',
    '务实主义',
    '狂热者',
    '干涉',
    '迅速的，敏捷的',
    '金钱的',
    '迟钝的，懒惰的',
    '多变的',
    '拖延的',
    '小心谨慎的',
    '虚伪，谎言',
    '谨慎的'
];

var resultList30 = [
    '猜测',
    '不重要的，不相 关的',
    '可证明的',
    '超自然的<br/>卓越的',
    '声称，断言',
    '假装，伪装',
    '承认',
    '不均衡的',
    '衰弱的，虚弱的',
    '强壮的',
    '混乱的',
    '漠不关心的，缺乏 热情的',
    '热情，狂热',
    '混合物',
    '不加区分的，不加 选择的',
    '安慰，调和',
    '全面的',
    '油嘴滑舌的',
    '真实的，准确的',
    '活力四射的',
    '大量的',
    '有声望的',
    '不寻常的，异常的',
    '倾向，偏好<br/>密切关系',
    '反对',
    '难懂的',
    '好争斗的',
    '深思熟虑<br/>故意的',
    '谨慎小心的',
    '有礼貌的',
    '自我感觉良好的， 自满的',
    '好争斗的<br/>言语刻薄的',
    '大量',
    '证明，证实',
    '组成多样的，混合 的',
    '不确定的',
    '支持者<br/>支持',
    '轻视'
];

var resultList31 = [
    '平凡普通的',
    '难懂的',
    '有趣的<br/>有说服力的',
    '唯利是图的',
    '典范',
    '引起争议的<br/>爱争吵的',
    '独裁主义的，专制 的',
    '克制，忍耐',
    '性格多变的',
    '清晰的',
    '攻击',
    '使...困惑',
    '使紧张，使急躁',
    '引起争论的',
    '怀疑他人动机不纯 的',
    '吸引',
    '使...生气',
    '薄弱的，不充分的',
    '使...稳定',
    '合适的<br/>有倾向的<br/>聪明的，灵巧的',
    '荒谬的',
    '边缘的，不重要的',
    '深刻的<br/>强烈的',
    '败坏，污染',
    '阻碍',
    '淘汰，取代',
    '抑制',
    '禁止',
    '限制',
    '各种各样的，多方面的',
    '繁重的，费力的',
    '限制',
    '繁重的，劳累的',
    '不友好的<br/>令人生畏的',
    '平静的',
    '难以处理的'
];

var resultList32 = [
    '离散的',
    '混乱的，混合的',
    '不走心的',
    '明显的',
    '要求髙的<br/>费力的',
    '晔众取宠，大肆宣 传',
    '机智幽默的评论',
    '(悲伤的）思考的',
    '古怪的，搞笑的',
    '禁欲主义，坚忍',
    '非常忙碌的',
    '费力的<br/>(对别人）髙标准 要求的',
    '拖延的',
    '反感的',
    '基于观察和实验',
    '实用的<br/>功利的，实用主义 的',
    '狭隘的，范围有限 的',
    '使...厌烦',
    '轻浮<br/>难以理解的',
    '灵巧的，精湛的',
    '微妙的<br/>杂乱无章的',
    '掐媚的',
    '谨慎的，小心的',
    '破坏',
    '默许，勉强同意',
    '难驾驭的，难处理 的',
    '尊敬',
    '憎恶，痛恨',
    '承认<br/>授予<br/>允许',
    '反驳，推翻',
    '不遵守<br/>违抗',
    '乐观的',
    '赞美',
    '赞美，致敬',
    '使...无效'
];

var resultList33 = [
    '欺骗性的',
    '可塑的',
    '能力，权力',
    '阻碍',
    '充满的',
    '自由决定的',
    '官僚机构',
    '回避，避开（话题）',
    '详细检查',
    '反驳',
    '掲路',
    '污点',
    '引诱',
    '玷污，破坏<br/>污点',
    '一贯的<br/>习惯做....的',
    '拦截',
    '迫使，强制',
    '阻碍，使窒息',
    '监控',
    '称赞<br/>推荐',
    '奇怪的，怪异的',
    '阻碍',
    '警告<br/>劝告',
    '危险的',
    '重要的',
    '处境危险的',
    '停滞',
    '僵硬的',
    '否认，拒绝',
    '(公开正式的）否 认',
    '中立的',
    '(无意中）显露',
    '驱逐',
    '公开支持',
    '驱逐',
    '支持<br/>支持（做不可数名词）<br/>制裁（做可数名 词）'
];

var resultList34 = [
    '私有的',
    '难懂的<br/>无法穿透的',
    '用于教育他人的',
    '自相矛盾的人或 事',
    '见多识广的<br/>来自四面八方的',
    '变化多端的',
    '唯利是图的',
    '不情愿的',
    '尖酸刻薄的',
    '讽刺，挖苦',
    '厌恶',
    '享受',
    '迷人的',
    '蔑视，鄙视',
    '颠覆，推翻<br/>破坏',
    '可感知的<br/>明显的',
    '温和的，适度的',
    '把委托给',
    '归因于,,',
    '精于世故的，老练的<br/>髙度复杂的',
    '意见一致',
    '后悔感，犯罪感',
    '矛盾的事物',
    '站不住脚的:',
    '绕过',
    '放大<br/>夸大',
    ',绕过，回避',
    '短暂的',
    '死亡，灭亡',
    '短暂的',
    '衰退',
    '恶化',
    '显眼的，明显的',
    '非常有趣的',
    '不重要的',
    '有害的'
];

var resultList35 = [
    '巨大的<br/>笨拙的',
    '无所不在',
    '希望',
    '否定，反驳',
    '髙质量的<br/>特别地<br/>特别的',
    '临时的',
    '不出名的<br/>匿名的',
    '公平的',
    '自白的',
    '详细阐述<br/>夸大',
    '详细阐述',
    '包住，围绕',
    '短暂的',
    '无法共存的，不可 兼容的',
    '聚集',
    '分层级',
    '无害的<br/>平淡的',
    '序曲',
    '荒凉的<br/>没有希望的',
    '掩饰<br/>证明......虚假错误',
    '削弱',
    '预示',
    '包括，包含',
    '一致的，同时发生 的',
    '砍',
    '普通的，通用的',
    '广泛的,全面的'
];

var resultList36 = [
    '培养',
    '易怒的，坏脾气的',
    '生活节制的',
    '引起争议的',
    '秘密的，鬼鬼崇崇 的',
    '无忧无虑，不操心',
    '根据观察或经验的',
    '不走心的',
    '极坏的',
    '不均衡的',
    '衰弱的，虚弱的',
    '强壮的',
    '混乱的',
    '年表',
    '概要',
    '歪曲的，错误的',
    '敏锐的',
    '被动防守的，防御 的',
    '惯常的',
    '疾病',
    '轻率，不谨慎',
    '诊断<br/>预言',
    '可变的，多变的',
    '敌对的',
    '敌对的',
    '矛盾的',
    '站不住脚的',
    '颠覆，推翻<br/>破坏',
    '使丰富',
    '扩大',
    '扩大，延长',
    '低玲浅唱',
    '即兴表演',
    '叫喊，尖叫',
    '低声唱歌',
    '发出难听的声音'
];

var resultList37 = [
    '史诗般的，伟大的',
    '平凡的，无聊的',
    '奇迹,,',
    '典型',
    '赞美',
    '削弱，减轻<br/>稀释',
    '相反，对立',
    '奢侈的<br/>浪费的<br/>挥霍，浪费',
    '日常的，例行的,,',
    ',,空的',
    '同质化的',
    '难以处理的',
    '而拥的',
    '证明',
    '拆穿，揭露...的 错误',
    '验证，证明....是真 实的',
    '先于',
    '缺点，恶习',
    '称赞，赞美<br/>赞美',
    '批评',
    '明显的',
    '费力的',
    '筛选',
    '获得；实现',
    '腐蚀',
    '修改，修饰',
    '能力',
    '混乱',
    '杂舌U混舌L',
    '难驾驭的',
    '不均匀的',
    '首要的，支配一切 的',
    '普通的，平庸的',
    '无聊的，令人昏昏 欲睡的',
    '睡眠，睡着度过',
    '不活跃的',
    '简洁的，用词少的',
    '使...困惑',
    '公平的'
];

var resultList38 = [
    '真诚的',
    '决心<br/>解决方案',
    '困境',
    '严格的',
    '似是而非的',
    '吵吵闹闹的',
    '脱离世俗的',
    '(团体的）气质， 氛围，信仰等',
    '平庸',
    '忧郁',
    '阻碍',
    '触发',
    '超越<br/>胜出，超出',
    '时尚',
    '根据观察或经验的',
    '实用的<br/>功利的，实用主义 的',
    '狭隘的，范围有限 的',
    '平息，镇压',
    '坚定的信仰，信念',
    '预测，预言',
    '促进',
    '与...相关<br/>适用，适合',
    '减缓',
    '史无前例的',
    '保证',
    '创新的',
    '紧急的',
    '情节',
    '典范',
    '混杂，混合物',
    '混合物',
    '承认<br/>授予<br/>允许',
    '让步',
    '否认<br/>放弃，屈服',
    '易怒的',
    '和蔼可亲的',
    '聪明的，睿智的',
    '脾气随和的'
];

var resultList39 = [
    '顶点，最髙点',
    '粗鲁的，无理性的',
    '使不安<br/>发出不和谐、难听的声音',
    ',,看起来合理的',
    '安抚的，调和的',
    '充满',
    '激怒，使不安:',
    '衰退，减少',
    '赋予权利，使能够<br/>提升的影响力',
    '过分扩展，承担过;:多务',
    '假名',
    '酬金',
    '充满的',
    '阻碍',
    '强制的',
    '使......负有义务',
    '通过模仿而赶超',
    '撤销（命令)',
    '调停，调整<br/>传达',
    '无聊的',
    '想象出',
    '剥夺',
    '健谈的，话多的',
    '真诚的',
    '可以理解的'
];

var resultList40 = [
    '恶化',
    '引起',
    '避免',
    '低估，轻视',
    '颠覆，推翻<br/>破坏',
    '支持',
    '夸大',
    '不情愿的',
    '孤独',
    '尊敬，敬意',
    '狂热',
    '通过模仿而赶超',
    '史无前例的',
    '使...困惑',
    '麻木，迟钝，懒散',
    '激发唤起',
    '喷出涌出',
    '陷防',
    '混舌的',
    '认为人性自私',
    '樹造的',
    '显然的明显的<br/>清晰地展示显露出',
    '减缓',
    '肖^弱',
    '迷宫',
    '迷宫',
    '复杂的',
    '流行的普遍的'
];

var resultList41 = [
    '开放的',
    '唤起的',
    '爱争论的<br/>有争议的',
    '启迪',
    '有歧义的',
    '过失，不法行为',
    '缺乏自信的',
    '谨慎的；一丝不苟的',
    '不能安抚的，毫不妥协的',
    '坚定的<br/>持续的',
    '中心思想<br/>(虚假地）声称',
    '克制，忍耐',
    '飘忽不定的没规律的',
    '博学的',
    '美学的<br/>吸引人的',
    '实际的',
    '本能',
    '后天习得的',
    '平凡的无聊的',
    '肖',
    '放弃',
    '字面的不夸张的',
    '表示尊敬的；给予荣誉的',
    '贬损氏毁',
    '争辩反对',
    '极小的',
    '微小的',
    '处处都有的',
    '虚无的<br/>天上的'
];

var resultList42 = [
    '使...瘫痪',
    '使泄气，使低落',
    '安抚，缓和',
    '使...生气',
    '阻碍',
    '稀释',
    '绕过，回避',
    '否定者，怀疑者',
    '易被打败的人<br/>易受影响的人',
    '吹噓，炫耀',
    '使...困惑',
    '吸引人的',
    '博学的',
    '尖亥扉利',
    '强制性的',
    '拒绝放弃',
    '设计谋戈',
    '摇摆不定犹豫<br/>摇摆',
    '反抗的难控制的:',
    '奇怪的古怪的',
    '引人注意的告炫的',
    '盈利赚钱的',
    '摒弃蔑视',
    '全画勺',
    '可以理解的',
    '$骨白勺<br/>难懂的<br/>不可靠的',
    '难懂的<br/>难以捕捉的',
    '无刚勺'
];

var resultList43 = [
    '不寻常的，异常的',
    '无序的，凌乱的',
    '集体的',
    '庞大而僵硬的',
    '过于夸张的',
    '潜藏的，潜在的',
    '恶心做作的',
    '朴素的，没有装饰的<br/>严肃的<br/>生活简朴的 ',
    '炫耀的',
    '极具价值的',
    '不寻常的<br/>杰出的，超常的',
    '习惯做....的',
    '日常的，例行的 ',
    '推测 ',
    '广泛的',
    '显著区别的',
    '使…衰弱，虚弱',
    '模仿',
    '装饰',
    '复杂的',
    '诱惑',
    '使...生气<br/>愤怒',
    '安抚',
    '使...生气，愤怒',
    '安抚，缓和',
    '使…清晰',
    '非典型的不寻常的',
    '难以克服的不可超趣勺',
    '坚持',
    '即兴表演',
    '避免，逃避',
    '可交换的',
    '持久的，耐用的',
    '行家',
    '大量',
    '过量',
    '和善的',
    '适合的<br/>宜人的，令人愉悦的'
];

var resultList44 = [
    '丰富的',
    '缺乏，少量',
    '阻碍',
    '激励',
    '理由',
    '超越',
    '处理',
    '减缓',
    '损毁，损伤',
    '同情的',
    '果断的',
    '任人唯亲',
    '晔众取宠',
    '盲目支持者',
    '犹豫不决',
    '综合',
    '不可思议的，难以 置信的',
    '灵敏的<br/>有倾向的',
    '淘汰，取代',
    '新兴的，新起的',
    '证明......是假的',
    '权威的，可信的',
    '活着的，有生命的<br/>鼓励，使...有活力',
    '时髦的',
    '冲动的',
    '缺乏新鲜感的',
    '刺激',
    '促进',
    '逼真',
    '乐观的',
    '热情友好的',
    '易怒的，坏脾气的',
    '好交际的，欢聚的',
    '使...生气',
    '激起...意识，激发...行动',
    '阻挠'
];

var resultList45 = [
    '除了......以外',
    '杰出的',
    '嘲笑，耻笑',
    '仔细检查',
    '装饰',
    '低估',
    '疏忽的，不注意的',
    '髙兴的',
    '无用的',
    '传染的',
    '吉祥的，吉利的',
    '显眼的，明显的',
    '模棱两可的，有歧 义的',
    '深入思考',
    '陌生的',
    '严厉批评',
    '使烦恼',
    '困难的',
    '不重要的',
    '停滞',
    '回响<br/>引起共鸣',
    '奇异的<br/>外来的，异国的',
    '重要的',
    '故障，问题',
    '(隐形的）问题， 难题',
    '结局',
    '标志，显著特征',
    '同意，赞同',
    '无私，利他主义',
    '多产的<br/>有创造力的，硕果',
    '颇丰的',
    '多产的（即可指农作物，也可以指思想、想法）<br/>短暂的'
];

var resultList46 = [
    '赋予人性',
    '感同身受',
    '彻底改动，重铸',
    '多变的',
    '坚定的，忠诚的',
    '关心的',
    '炫耀的',
    '突发奇想',
    '客观的',
    '一针见血的，深刻尖锐的',
    '损害，使无效',
    '重视，尊敬',
    '（因人不诚实而）批评打击',
    '保证',
    '难懂的',
    '暂时的，临时的',
    '强硬的，不懂动感情的',
    '询问',
    '无害的<br/>不惹人厌烦的',
    '疑惑的<br/>戏弄的，嘲笑的',
    '粗鲁的',
    '回避的，闪烁其词的',
    '精细的,精心的<br/>精心制作<br/>详细阐述',
    '使...生气<br/>愤怒',
    '虚弱的，无能的<br/>粗心的，不负责任的',
    '不知情的，无意识的；无心的',
    '<br/>抱怨的',
    '信仰虔诚的<br/>虚伪的',
    '说教的，好为人师的',
    '假装道德高尚的,假正经的',
    '痛苦的的',
    '一潭死水',
    '垂涎',
    '困难的<br/>费力的',
    '繁重的，劳累的',
    '阻止，先发制人<br/>取代<br/>抢占',
    '前言'
];

var resultList47 = [
    '吵吵闹闹的',
    '令人反感的',
    '超自然的',
    '根据观察或经验的',
    '声音洪亮的',
    '铭刻，牢记',
    '有益的，有益健康的',
    '深思熟虑<br/>故意的',
    '有序的',
    '短暂的',
    '不可避免的，一定<br/>发生的',
    '证据，证词',
    '奇闻异事',
    '承认<br/>授予<br/>允许',
    '预示',
    '妥协，让步<br/>降低',
    '揭发，揭露',
    '容忍，忍受',
    '否认，拒绝',
    '有健康的',
    '超出，超过<br/>遮盖',
    '阻止',
    '伪造，造假<br/>努力形成',
    '易怒的<br/>爱惹事的，不服管的',
    '供应商',
    '吹毛求疵的',
    '贪裝的人',
    '不活泼的',
    '辱骂',
    '陈词滥调',
    '好争斗的',
    '好争斗的<br/>言语刻薄的',
    '目空一切的高傲白勺',
    '两极分化',
    '安抚调和',
    '敏锐的',
    '普通无聊的毫无亮点的',
    '使陶醉沉醉'
];

var resultList48 = [
    '鬼鬼崇崇白勺',
    '典型',
    '引起愤怒的',
    '短暂的',
    '使...惊讶',
    '秘密的，鬼鬼崇崇 的',
    '决定，决心要做',
    '憎恨，生气',
    '令人烦恼的',
    '秘密的，隐蔽的',
    '平等的，公平的',
    '费力的',
    '证实，使有效',
    '合作',
    '摒弃，蔑视',
    '沉思，仔细思考',
    '诉讼当事人',
    '证据的',
    '使...恶化',
    '引用...证明',
    '使...困惑',
    '复制',
    '复杂的',
    '冗长无聊的 ',
    '千篇一律的',
    '难懂的，复杂的',
    '空的<br/>愚蠢的',
    '复杂难懂的',
    '刻板的，俗套的',
    '坚韧不妥协的<br/>理性的',
    '吸引人的',
    '同情的',
    '精力充沛的',
    '恢复',
    '可靠的；稳定的'
];

var resultList49 = [
    '"大量',
    '少量',
    '(引起混乱的）巨变',
    '使...泄气',
    '不重要的',
    '诱骗',
    '吸引人的',
    '心灵受创伤的',
    '纪念品',
    '随行人员',
    '正直',
    '助长，促进<br/>养育，照料',
    '责难',
    '冗长无聊的',
    '独有的，排外的',
    '多变的',
    '广泛的',
    '新颖的，创新的',
    '欢呼，暍彩',
    '首要的，支配一切的',
    '混合',
    '先锋部队',
    '爱好和平的',
    '漠不关心的，缺乏 热情的',
    '朴素的，没有装饰的<br/>严肃的<br/>生活简朴的',
    '爱好和平的',
    '尖刻，犀利'
];

var resultList50 = [
    '倾向，偏好',
    '辱骂，侮辱',
    '坚定的',
    '好争斗的',
    '表达过多感情的',
    '合并',
    '平静的<br/>稳定不变的',
    '巨大的',
    '不重要的，不相关的<br/>外部的',
    '使...进入某种状态',
    '分散',
    '骤然下跌',
    '使...分散',
    '驱逐<br/>取代，代替',
    '表面的，虚假的',
    '相反，对立',
    '简洁的',
    '极好的<br/>(通过可怕的细节)令人兴奋的<br/>骇人听闻的',
    '巨大的',
    '完满的，圆满的',
    '神谕，睿智的回答',
    '预言的',
    '不能解释的',
    '不吉利的',
    '分散，转移（注意力，精神）<br/>通过转移注意力使人愉悦',
    '毁灭，毁坏',
    '分水龄',
    '改善，提升',
    '使恶化',
    '减轻'
];

var resultList51 = [
    '不切实际的',
    '先见，预知',
    '可行的<br/>可以存活的',
    '冷漠的，无动于衷的<br/>面无表情的',
    '单独的',
    '迟钝的',
    '极其严苛的',
    '贪婪的',
    '耗尽',
    '守旧的',
    '鼓舞，鼓励',
    '阻碍',
    '熟悉的',
    '(虚假地）声称',
    '难懂的，只有少数人懂得的',
    '当中',
    '混乱',
    '违背自己利益的，弄巧成拙的',
    '夸大，吹捧<br/>抬髙身价，提髙地位',
    '持续，使...继续',
    '滥用',
    '过时的',
    '不公平的对待<br/>误用',
    '（论点）经不起反驳的，站不住脚的',
    '陈词滥调',
    '显示优越感<br/>放下身段做...',
    '完全地，彻底地',
    '违法行为',
    '欺诈的',
    '情绪失控，举止失常',
    '诽谤，辱骂',
    '阻碍',
    '使痛苦'
];

var resultList52 = [
    '阻止',
    '炫耀的',
    '损害',
    '假正经的',
    '抨击',
    '揭露',
    '令人反感的',
    '陈词滥调',
    '恋爱',
    '诱骗',
    '辱骂',
    '易怒的',
    '诉讼当事人',
    '愤怒的',
    '冗长的',
    '稳定的',
    '烦恼的',
    '心灵创伤的'
];

var resultList53 = [
    '快速增长',
    'n.灾难',
    '广泛的，蔓延的',
    '嘲笑，嘲弄',
    '神圣而不可侵犯的',
    '短暂的',
    '可塑的',
    '平等的',
    '自治的<br/>独立自主的',
    '临近的',
    '危害',
    '人为的',
    '相互的，共同的',
    '明显的，显眼的',
    '强壮的',
    '短暂的',
    '笨拙的',
    '体积庞大而笨重的',
    '古怪的',
    '倾向，偏好',
    '摇摆不定，犹豫',
    '摇摆不定',
    '胆小',
    '加强',
    '相反的',
    '冷血的没有同情心的',
    '无害的<br/>温和的善良的',
    '主流的<br/>符合传统的',
    '不寻常的异常的',
    '体现',
    '全部节目详单',
    '环境背景:',
    '直白的坦诚的',
    '放大',
    '改善提升',
    '外向的人爱社交:者',
    '必要的重要的',
    '不可缺少的',
    '本着良心的<br/>勤奋的'
];

var resultList54 = [
    '(数量，效果）相 当的',
    '证明...的清白',
    '禁止',
    '告别',
    '开脱罪责',
    '和蔼可亲的',
    '热情洋溢的',
    '易怒的，坏脾气的',
    '情绪激动且不髙兴 的',
    '慎重的',
    '年表',
    '概要',
    '错误的',
    '敏锐的',
    '低估，轻视',
    '通过模仿而赶超',
    '赞美',
    '平等的',
    '时代错乱',
    '帝王的，皇室的',
    '克制，忍耐',
    '冲动的，鲁莽的',
    '粗鲁的，粗野的',
    '对女人彬彬有礼的，骑士风度的',
    '小心谨慎的',
    '停止，不再',
    '(如大百科全书般）全面的',
    '冗长无聊的<br/>跑题的，冗长的',
    '闲逛的',
    '霸道总裁儿的',
    '高尚的',
    '断言，宣称',
    '毋庸置疑的',
    '天才的，聪明的 ',
    '谦虚的，低调的',
    '煽动叛乱的'
];

var resultList55 = [
    '同意<br/>同时发生',
    '博学的',
    '引起争议的<br/>爱争吵的',
    '有条理的',
    '新颖的，创新的',
    '刻板的，俗套的',
    '盈利的，赚钱的',
    '(依据已知信息） 推测',
    '与...相似',
    '缺点',
    '拒绝承认<br/>使被怀疑<br/>破坏名声',
    '降低......的重要性',
    '阻止',
    '注定（失败）',
    '过量',
    '难题',
    '阻止',
    '放弃',
    '地方性的，流行的<br/>(问题、情形）常 见的',
    '占主导地位的，统 治的',
    '精心的，精细的<br/>精心制作<br/>详细阐述',
    '实用的<br/>功利的，实用主义 的',
    '使平衡',
    '减少，下降<br/>结束<br/>(月亮的）亏',
    '衰落<br/>退潮',
    '值得注意的',
    '慷慨，大方',
    '正直',
    '能说会道的，能言'
];

var resultList56 = [
    '无知的',
    '责难',
    '吹噓',
    '轻视',
    '不受限制的',
    '传播，散布',
    '宏伟的',
    '腐烂，退化',
    '仓库',
    '胜利，成就',
    '分散的',
    '使...厌烦',
    '浸润，浸泡<br/>全心沉浸在...中',
    '有价值的人或物',
    '轻率无礼的',
    '偏担的，偏向的',
    '衰落，不活跃',
    '快速增长',
    '拒绝，放弃',
    '兴旺发达',
    '困境',
    '困境',
    '策略',
    '(短期大幅）上升',
    '增长',
    '前兆<br/>预兆',
    '使平静<br/>暂时的平静，间歇',
    '前兆，预示',
    '暂歇，休息',
    '使...满意',
    '诱惑',
    '易怒的',
    '(无意中）显露'
];

var resultList57 = [
    '接受<br/>拥抱',
    '夸张',
    '骗子',
    '蔑视，鄙视',
    '喜爱',
    '尽管',
    '有教养的，彬彬有礼的',
    '充满激情的',
    '(弓丨起混乱的）巨,,,变',
    '即将发生的',
    '严祠勺<br/>坚定的',
    '先见，预知',
    '预言的',
    '激情的，热烈的',
    '筛选',
    '压迫的',
    '废止，使无效<br/>镇压，平息',
    '诱惑',
    '初始的',
    '缺乏',
    '清楚的明确的',
    '超越<br/>胜出超出<br/>克服战胜',
    '反融勺',
    '地方的<br/>狭隘的范围有限的',
];

var resultList58 = [
    '推断',
    '可以解释的',
    '恐怖的，可怕的<br/>令人惊叹的<br/>艰巨的',
    '似是而非的',
    '不可逆的',
    '皱眉<br/>厌恶',
    '广泛的<br/>猖撅的',
    '损坏，破坏',
    '翻动',
    '无限的<br/>极大的',
    '回避，避开（话题）',
    '仔细检查',
    '否认，拒绝',
    '使困惑<br/>驳斥，证明....错误<br/>混淆',
    '限制',
    '以假乱真的，模仿 的',
    '夸大',
    '违反常理的，与直 觉相反的',
    '充满的',
    '赞美',
    '指控',
    '赞美<br/>提升',
    '恢复',
    '强烈斥责',
    '规定（较髙的）价 格（引申为赞美）'
];

var resultList59 = [
    '执着的，固执的',
    '缺乏自信的，胆怯 的',
    '谨慎的；一丝不苟 的',
    '不能安抚的，毫不 妥协的',
    '轻而薄的，虚无缥 缈的',
    '设计，谋划',
    '吉祥物',
    '快速移动',
    '过时的',
    '抵消，使无效',
    '典范',
    '倾斜',
    '拧<br/>略微调整',
    '争论，辩论',
    '清楚有力地表达',
    '牢固地确立',
    '支持',
    '脱离，偏离',
    '屈服',
    '畏缩',
    '信仰虔诚的<br/>虚伪的',
    '说教的，好为人师<br/>的',
    '抱怨的',
    '围绕，包围',
    '假装道德髙尚的，<br/>假正经的',
    '痛苦的',
    '到处存在的，广泛<br/>的',
    '提纯<br/>提升，提局',
    '处处都有的'
];

var resultList60 = [
    '大量的',
    '狂怒，暴怒',
    '对待方式',
    '严厉的',
    '严肃认真的',
    '沮丧的',
    '掩盖<br/>与...相矛盾<br/>证明...为假',
    '合并',
    '泄露',
    '虚构的',
    '标志，典型的特征',
    '能说会道的，能言 善辩的',
    '震惊，惊讶<br/>惊世之作',
    '谨慎的；一丝不苟 的',
    '反抗的，难控制的',
    '奇怪的，古怪的',
    '引人注意的，酷炫 的',
    '坚固的，顽强的',
    '斥责，批评',
    '暂歇，休息',
    '启迪',
    '谨慎的小心的',
    '加速',
    '为他人着想的圆滑的',
    '克制忍耐',
    '共谋协力',
    '广泛的<br/>娼獗的',
    '违后而来接着发生',
    '激励鼓励',
    '非典型的反常的',
    '相伴随的与同时发生的',
    '难懂的<br/>难以捕捉的',
    '懒惰',
    '微光',
    '帝国的',
    '行头装饰品',
    '庄严的肃穆的',
    '庄严威武的',
];

var resultList61 = [
    '碎石，残余物',
    '不重要的<br/>外部的',
    '竞争，对抗',
    '聚集',
    '无意识的，遗忘的',
    '杰出，显者',
    '削弱',
    '授权<br/>提升...的影响力',
    '投降，放弃',
    '慢慢收集',
    '淘汰，取代',
    '停止<br/>踌躇',
    '不同的',
    '反馈',
    '静态的',
    '持续，使...继续',
    '短暂的',
    '危险的',
    '过量的',
    '稀缺的 I',
    '减少，下降|',
    '真实的',
    '详细的<br/>有限的',
    '终结的，最终的',
    '不足的，少的 ',
    '阐释，阐明',
    '使…困惑'
];

var resultList62 = [
    '自私的',
    '掩盖<br/>与...相矛盾<br/>证明...为假',
    '合并',
    '泄露',
    '天真的',
    '预谋，提前构画',
    '操控',
    '证据，证词',
    '奇闻异事',
    '最显著的，主导的',
    '可以这样说地',
    '有影响力的',
    '冗长的',
    '参考书目',
    '逃跑，逃避<br/>使…无法理解 <br/>使....无法得到',
    '坚固的，顽强的',
    '斥责，批评',
    '暂歇，休息',
    '要求髙的<br/>费力的',
    '繁重的，费力的 ',
    '反抗的，难控制的 ',
    '奇怪的，古怪的',
    '引人注意的，酷炫的',
    '谴责',
    '辱骂',
    '长篇痛骂',
    '开脱罪责',
    '演讲，报告',
    '证明...的清白'
];

var resultList63 = [
    '折磨，使...痛苦',
    '难懂的，复杂的',
    '不合理的，难以置信的',
    '先锋派，前卫派<br/>前卫的，先锋的',
    '茂视，鄙视',
    '培养',
    '极好的<br/>(通过可怕的细 节)令人兴奋的，骇人听闻的',
    '降低......的重要性',
    '阻止',
    '注定（失败）',
    '绕过',
    '共谋，协力',
    '广泛的<br/>猖撅的',
    '随后而来，接着发 生',
    '激励，鼓励',
    '非典型的，反常的',
    '相伴随的，与...同 时发生的',
    '安协，让步<br/>降低<br/>破坏',
    '宣布',
    '宣称',
    '否认',
    '(无意中）显露',
    '引起争论的<br/>刺激的',
    '限制',
    '使...喜悦或兴奋',
    '使......敌对',
    '引起争议的<br/>爱争吵的',
    '无聊的，普通的<br/>行人',
    '使...困惑',
    '平凡的，无聊的',
    '非常有趣的',
    '赞美',
    '不直接的<br/>含沙射影的，讽刺 挖苦的',
    '少量',
    '真诚的',
    '不足的，少的'
];

var resultList64 = [
    '顶点，最局点',
    '粗鲁的，无理性的',
    '使...不安<br/>发出不和谐、难听的声音',
    '看起来合理的',
    '安抚的，调和的',
    '真理',
    '告别',
    '坚决<br/>解决',
    '否认',
    '轻视',
    '难懂的<br/>难懂的，只有少数',
    '人懂得的',
    '全面的',
    '引起争论的',
    '规定<br/>保证',
    '传播，散布',
    '笨重的<br/>无聊的',
    '根据观察或经验的',
    '赞美的',
    '奉...为神，尊苟文',
    '(拆穿，揭露…的)错误',
    '夸大，吹捧<br/>抬髙身价，提髙地位',
    '不能安抚的，毫不妥办的',
    '不妥协的，固执的',
    '无懈可击的',
    '完全的<br/>不合格的',
    '变化多端的',
    '过时的',
    '多变的<br/>易激动的',
    '过时的',
    '极端爱国的',
    '赞助<br/>摆出髙人一等的态 度对待',
    '迷惑，欺骗',
    '至今'
];

var resultList65 = [
    '投降，屈服<br/>产出',
    '不寻常的，异常的',
    '难懂的',
    '秘密的，鬼鬼崇崇的',
    '决定，决心要做',
    '憎恨，生气',
    '令人烦恼的',
    '秘密的，隐蔽的',
    '平等的，公平的',
    '分配，分发',
    '夸大',
    '小心谨慎的，挑剔的',
    '夸大',
    '即兴表演',
    '撤销（命令）',
    '相等的，相似的',
    '平等',
    '广泛的,全面的<br/>开放的',
    '分层级',
    '事件发生地点',
    '隔离，隐居<br/>偏僻',
    '昂贵的<br/>富裕的',
    '大量的',
    '奉承的',
    '生活朴素的',
    '唯利是图的',
    '暗指',
    '结果，后果<br/>分支',
    '暂歇，休息',
    '欺骗',
    '使...困惑',
    '使浮起来<br/>鼓励',
    '无忧无虑，不操心',
    '冷漠，淡泊',
    '欣然同意',
    '热情友好的',
    '好交际的，欢聚的',
    '超出，超过<br/>遮盖',
    '被冲走，滤去',
    '到处存在的，广泛的',
    '令人不快的',
    '难闻的，恶臭的',
    '芬芳的',
    '有害的，恶臭的',
    '不惹人厌烦的<br/>缓解疼痛的'
];

var wordlist66 = [
    'contemptuous',
    'ignorant',
    'decry',
    'boast',
    'downplay',
    'devolve',
    'acrimony',
    'comity',
    'mordant',
    'thrive',
    'apropos',
    'churlish',
    'cagey',
    'emulate',
    'adjudicate',
    'advocate',
    'adversary',
    'contemplate',
    'counter',
    'eschew',
    'conspicuous',
    'transmit',
    'proximity',
    'furtive',
    'compensate',
    'offset',
    'polemical',
    'precarious',
    'enterprising',
    'rapacious',
    'avaricious'
];

var resultList66 = [
    '鄙视的',
    '无知的',
    '责难',
    '吹噓',
    '轻视',
    '衰落<br/>(权力、责任）移 交',
    '尖刻，犀利',
    '友好，和谐',
    '尖酸刻薄的',
    '兴旺发达',
    '合适的<br/>至于...',
    '不礼貌的',
    '守口如瓶的<br/>警惕的<br/>聪明的',
    '通过模仿而赶超',
    '裁定，宣判',
    '支持者<br/>支持',
    '对手，敌手',
    '深入思考',
    '反驳',
    '避免',
    '显眼的，明显的',
    '传输，传递',
    '临近',
    '鬼鬼崇崇白勺',
    '弥补<br/>抵消',
    '抵消',
    '好争论的',
    '处境危险的',
    '有事业心的，有进 取心的',
    '贪婪的',
    '贪婪的'
];

var wordlist67 = [
    'minuscule',
    'entail',
    'facilitate',
    'rote',
    'condone',
    'dishearten',
    'pedestrian',
    'knotty',
    'mundane',
    'dire',
    'wane',
    'deteriorate',
    'bighearted',
    'inflammatory',
    'gloomy',
    'puerile',
    'embed',
    'vapid',
    'sagacious',
    'banal',
    'opaque',
    'remarkable',
    'felicitous',
    'prolific ',
    'abbreviate',
    'affinity ',
    'intricate',
    'sectarian',
    'baroque',
    'transcend',
    'provincial ',
    'contingent',
    'abstruse ',
    'explicable'
];

var resultList67 = [
    '极小的',
    '包括，包含',
    '辅助，帮助',
    '死记硬背',
    '原谅，认可',
    '使...士气低落',
    '无聊的，普通的<br/>行人',
    '复杂的',
    '平凡的，无聊的',
    '可怕的，严重的',
    '减少，下降',
    '恶化',
    '慷慨的，宽大的',
    '煽动性的',
    '悲伤的',
    '稚嫩的，幼稚的',
    '嵌入',
    '无聊的',
    '聪明的，睿智的',
    '无聊的',
    '难懂的<br/>不透明的',
    '值得注意的，不同寻常的',
    '合适的<br/>喜悦的，令人愉悦的',
    '多产的',
    '缩短',
    '倾向，偏好',
    '复杂的',
    '獅益的<br/>挑剔的',
    '奢华的，复杂的',
    '超越<br/>胜出，超出',
    '眼光狭益的',
    '偶然的',
    '难以理解',
    '可以解释的'
];

var wordlist68 = [
    'eclipse',
    'bolster ',
    'corroborate',
    'outstrip',
    'sacrosanct',
    'ephemeral ',
    'malleable',
    'egalitarian',
    'euphemism',
    'elusive',
    'naysayer',
    'pushover',
    'braggart',
    'absorbing',
    'quixotic',
    'skullduggery',
    'incivility',
    'entail',
    'hamstring',
    'revitalize',
    'impair',
    'invigorate',
    'evanescent',
    'prosaic',
    'nullify',
    'accentuate',
    'trade-off',
    'foretell',
    'engender'
];

var resultList68 = [
    '使...不重要<br/>超出',
    '支持',
    '佐证，提供证据证明',
    '胜出，超出',
    '神圣而不可侵犯的 ',
    '短暂的 可塑的',
    '平等的',
    '委婉语',
    '难懂的<br/>难以捕捉的',
    '否定者，怀疑者',
    '易被打败的人 易受影响的人',
    '容易的事',
    '吹牛者',
    '吸引人的',
    '不切实际的<br/>变化多端的，变幻莫测的',
    '欺骗，作假',
    '不礼貌',
    '包括，包含',
    '损坏',
    '使...复活',
    '损害',
    '使...有活力',
    '短暂的',
    '普通寻常的<br/>散文的<br/>缺乏创意的',
    '使...无效',
    '强调',
    '权衡',
    '预言，预测',
    '产生'
];

var wordlist69 = [
    'aloof',
    'snob',
    'wastrel',
    'marginal',
    'onerous',
    'efficacious',
    'auspicious',
    'benign',
    'salutary',
    'palliate',
    'analgesic',
    'urge',
    'apprehend',
    'sanguine',
    'anxious',
    'chimera',
    'anachronism',
    'conundrum',
    'rambling',
    'hone',
    'germane',
    'obsolete',
    'outmoded'
];

var resultList69 = [
    '冷漠的，置身事外的',
    '势利小人',
    '浪费的人',
    '边缘的，不重要的',
    '繁重的，费力的',
    '有效果的',
    '吉兆的，幸运的',
    '无害的',
    '温和的，善良的',
    '有益的，有益健康的',
    '减缓',
    '止痛药',
    '强烈要求',
    '逮捕<br/>理解<br/>害怕，恐惧',
    '乐观的',
    '焦虑的',
    '幻想',
    '时代错误',
    '难题<br/>跑题的，冗长的',
    '闲逛的',
    '相关的',
    '过时的',
    '过时的'
];

var wordlist70 = [
    'craft',
    'ingenious',
    'scrupulous',
    'animadversion',
    'culmination',
    'divination',
    'compelling',
    'unflinching',
    'slapdash',
    'erudite',
    'revisionist',
    'robust',
    'embargo',
    'corroborate',
    'dispel',
    'hazardous',
    'insidious',
    'aberrant',
    'castigate',
    'chastise',
    'endorse',
    'commend',
    'profusion',
    'conducive',
    'hinder',
    'devastate',
    'deleterious',
    'essential',
    'indispensable'
];

var resultList70 = [
    '工艺，手艺',
    '天才的，聪明的',
    '小心谨慎的<br/>有道德的，有良心的',
    '批判，责骂',
    '最终，结果',
    '预言，占卜',
    '有趣的<br/>有说服力的',
    '坚定的，不退缩的<br/>(表达）直白的',
    '草率的，粗心大意的',
    '博学的',
    '修正主义者',
    '强壮的<br/>稳定无误的',
    '禁止',
    '佐证，提供证据证明',
    '驱散，消除',
    '危险的',
    '阴险的，暗中为害 的',
    '不正常的',
    '严厉批评',
    '谴责',
    '公开支持',
    '赞美',
    '大量',
    '有益的，有帮助的',
    '阻碍',
    '严重破坏',
    '有害的',
    '重要的，必要的',
    '不可缺少的'
];

var wordlist71 = [
    'render',
    'enamor',
    'prescient',
    'concede',
    'bedrock',
    'imperative',
    'compromise',
    'affinity',
    'impartial',
    'expedite',
    'constrain',
    'deter',
    'exacerbate',
    'lament',
    'appraise',
    'bootless',
    'tendentious',
    'indifferent',
    'deprecate',
    'plausible',
    'transcend',
    'provincial ',
    'contingent',
    'naive',
    'premeditate',
    'manipulate',
    'explicable ',
    'minuscule ',
    'malady ',
    'assuage',
    'plague',
];

var resultList71 = [
    '使...进入某种状态',
    '使...喜爱',
    '预知的，有先见之 明的 ',
    '承认',
    '根基',
    '重要的<br/>命令，规则',
    '安协，让步<br/>降低<br/>破坏',
    '倾向，偏好',
    '公正的，不偏不倚的',
    '加速，加快',
    '限制',
    '阻止',
    '使...恶化',
    '哀叹，哀悼',
    '评估',
    '无用的',
    '偏担的，偏向的',
    '漠不关心的<br/>平庸的',
    '贬损诋毁',
    '看起来合理的<br/>表面上可行的',
    '超越<br/>胜出，超出',
    '眼光狭隘的',
    '偶然的',
    '天真的:',
    '预谋，提前构画',
    '操控',
    '可以解释的',
    '极小的',
    '疾病',
    '(安抚，缓和)',
    '困扰<br/>痕疫，灾害'
];

var wordlist72 = [
    'assemble',
    'haphazard ',
    'burlesque',
    'satire',
    'pastiche',
    'parody',
    'irreverent',
    'sympathetic',
    'sycophantic ',
    'censorious',
    'pedantic',
    'dissemble',
    'molder',
    'pretentious',
    'catalyst',
    'disperse',
    'garrulous',
    'mercurial',
    'bridle',
    'incursion',
    'expedite',
    'stump',
    'riddle',
    'paragon',
    'conundrum',
    'cast-iron',
    'reproach',
    'respite',
    'sober',
    'posit',
    'ponder',
    'one-stop'
];

var resultList72 = [
    '聚集，集合',
    '无序的，凌乱的',
    '通过滑稽的模仿而讽刺',
    '讽束',
    '【贬】模仿作品',
    '拙劣的模仿',
    '不敬的，无礼的:',
    '赞同的<br/>同情的',
    '奉承的',
    '平的',
    '卖弄知识的',
    '隐藏伪装（感情、',
    '意见）',
    '腐烂，退化',
    '炫耀的',
    '催化剂',
    '使...分散',
    '话多的',
    '性格多变的',
    '限制，管控',
    '侵入，侵犯<br/>进入',
    '加速，加快',
    '难题，谜题',
    '典范，模范',
    '难题',
    '坚固的，顽强的',
    '斥责，批评',
    '暂歇，休息  I',
    '严肃认真的',
    '假定，假设',
    '沉思，仔细思考',
    '一站式的，全方位的'
];

var wordlist73 = [
    'epic',
    'mundane',
    'glamorous',
    'renowned',
    'disavow',
    'understate',
    'obfuscate',
    'concoct',
    'sensational',
    'abnegate',
    'recapitulate',
    'accrete',
    'versatile',
    'adjunct',
    'routine',
    'deceptive',
    'exceptional',
    'evident',
    'fragile',
    'decadent',
    'provocative',
    'confine',
    'exhilarate',
    'abound',
    'proliferate',
    'stagnate',
    'coalesce',
    'robust',
    'neutralize',
    'impair',
    'outstrip'
];

var resultList73 = [
    '史诗般的，伟大的',
    '平凡的，无聊的',
    '有吸引力的',
    '出名的',
    '否认',
    '轻描淡写<br/>表达中故意带有限制',
    '使...困惑',
    '使...昏暗<br/>编造，捏造',
    '极好的<br/>(通过可怕的细节)令人兴奋的，骇人听闻的',
    '否认<br/>放弃，屈服',
    '总结',
    '逐渐增长',
    '多变的',
    '附属物',
    '日常的，例行的',
    '欺骗的',
    '不寻常的<br/>杰出的，超常的',
    '明显的',
    '脆弱的',
    '(思想）堕落的， 颓废的<br/>三俗的(庸俗、低 俗、媚俗的）',
    '引起争论的<br/>刺激的',
    '限制',
    '使...喜悦或兴奋',
    '富于，充满',
    '快速增长',
    '停滞',
    '聚合，团结',
    '强壮的<br/>稳定无误的',
    '抵消，使无效',
    '损害',
    '胜出，超出'
];

var wordlist74 = [
    'impede',
    'nonchalant',
    'acumen',
    'tantamount',
    'germane',
    'de-emphasize',
    'check',
    'doom',
    'bypass',
    'strew',
    'douse',
    'perpetuate',
    'capture',
    'extinguish',
    'cast-iron',
    'reproach',
    'respite',
    'one-stop',
    'ponder',
    'concede',
    'outlook',
    'prescient',
    'circumspect',
    'magisterial ',
    'sanguine ',
    'baffle ',
    'synergy',
    'premise',
    'penalty  ',
    'naive',
    'premeditate',
    'manipulate',
    'extraordinary',
];

var resultList74 = [
    '阻碍',
    '漠不关心的',
    '机智，精明',
    '(数量，效果）相 当的',
    '相关的',
    '降低......的重要性',
    '阻止',
    '注定（失败）',
    '绕过',
    '散播',
    '熄灭',
    '持续，使...继续',
    '俘获，夺得',
    '熄灭',
    '坚固的，顽强的',
    '斥责，批评',
    '暂歇，休息',
    '一站式的，全方位 的',
    '沉思，仔细思考',
    '承认',
    '观点',
    '预知的，有先见之明的',
    '谨，瞋的',
    '权威的',
    '乐观的',
    '使困惑',
    '协同乍用',
    '前提',
    '惩罚',
    '天真的:',
    '预谋，提前构画',
    '操控',
    '非凡的<br/>特别的'
];

var wordlist75 = [
    'indisputable',
    'plausible',
    'uncontested',
    'bewilder',
    'explicable',
    'minuscule',
    'omission',
    'subsequent',
    'grant',
    'aversion',
    'altruistic',
    'illusory',
    'mimic',
    'paradigm',
    'tweak',
    'controvert',
    'articulate',
    'entrench',
    'bolster',
    'circumvent',
    'undermine',
    'intoxicate',
    'discount',
    'prevalent',
    'augment',
    'sidestep',
    'vilify',
    'endorse',
    'studied',
    'negligible',
    'explicit',
    'obfuscate',
];

var resultList75 = [
    '不容置疑的',
    '看起来合理的<br/>表面上可行的',
    '无异议的，无竞争的',
    '使...困惑',
    '可以解释的',
    '极小的',
    '疏忽，遗漏',
    '后来的，随后的',
    '承认<br/>授予<br/>允许',
    '厌恶',
    '无私，利他主义',
    '虚假的',
    '模仿',
    '典范',
    '拧<br/>略微调整',
    '反驳，争论',
    '清晰有效地说',
    '牢固地确立',
    '支持',
    '绕过，回避',
    '削弱',
    '使...陶醉，沉醉',
    '低估，轻视',
    '流行的，普遍的',
    '放大<br/>补充',
    '回避，绕过',
    '诽谤，辱骂',
    '公开支持<br/>代言...产品',
    '故意的，精打细算的<br/>博学的',
    '不重要的',
    '明白的，清楚的',
    '使...困惑<br/>使...昏暗'
];

var wordlist76 = [
    'cordial',
    'heretofore',
    'stilted',
    'impertinent',
    'nostalgia',
    'precedent',
    'cosmopolitan',
    'suffice',
    'elicit',
    'vindicate',
    'invalidate',
    'vitiate',
    'bolster',
    'choke',
    'spur',
    'codify',
    'foster',
    'hail',
    'augment',
    'acclaim',
    'hefty',
    'circuitous',
    'truncate',
    'strenuous',
    'arduous',
    'insular',
    'mercenary',
    'intransigent ',
    'abandon',
    'perpetuate',
    'vulgar',
    'adroit',
    'flagrant',
    'crass',
    'culmination',
    'purview',
    'overreach',
    'contingency'
];

var resultList76 = [
    '热情友好的',
    '迄今为止',
    '不自然的，僵硬的',
    '粗鲁的<br/>不相关的',
    '思乡<br/>思念过去',
    '先例<br/>(法律中的）先例',
    '见多识广的<br/>来自四面八方的<br/>世界各地都有的',
    '足够',
    '引起',
    '证明...的清白',
    '削弱，使...无效',
    '损害，使无效',
    '支持',
    '抑制',
    '刺激',
    '整理',
    '促进',
    '赞美',
    '放大',
    '称赞，暍彩',
    '又大又重的',
    '兜圈子的，不直接 的',
    '缩短',
    '费力的',
    '困难的<br/>费力的',
    '孤立的<br/>思想狭、守旧的',
    '唯利是图的',
    '不妥协的，固执的',
    '放纵<br/>放弃',
    '(持续，使继续)',
    '粗俗的<br/>普通大众的',
    '灵的',
    '臭名日召著的',
    '粗#的<br/>(用于贬义词加强语气的）非常的',
    '最终，结果',
    '视里予',
    '里予心勃勃而失败<br/>不住，不自量',
    '可能事件'
];

var wordlist77 = [
    'trenchant',
    'keen',
    'inclusive',
    'complacent',
    'integrity',
    'mercurial',
    'amorphous',
    'ubiquitous',
    'manifest',
    'exiguous',
    'insipid',
    'infectious',
    'captious',
    'liability',
    'pathological',
    'inadvertent',
    'maelstrom',
    'hew',
    'override',
    'mitigate',
    'forage',
    'eccentric',
    'meager',
    'salutary',
    'proscribe',
    'trendy',
    'exacting',
    'abate',
    'civility',
    'comity',
    'plunder',
    'glut',
    'revival',
    'hodgepodge',
    'surfeit',
    'modicum',
    'dearth'
];

var resultList77 = [
    '尖酸刻薄的',
    '犀利的，一针见血的',
    '对...感兴趣，喜欢<br/>感觉敏锐的<br/>锋利的',
    '广泛的,全面的<br/>开放的',
    '自我感觉良好的， 自满的',
    '正直',
    '性格多变的',
    '无固定形状的',
    '到处存在的，广泛的',
    '显然的，明显的<br/>清晰地展示，显露出',
    '极其缺乏的',
    '无聊的',
    '传染的',
    '挑刺的，吹毛求疵的',
    '累赘<br/>责任，义务',
    '极端的<br/>病态的',
    '粗心的，不留意的<br/>不故意的',
    '大漩涡（引申为混乱，动乱）',
    '遵守',
    '否决，推翻<br/>凌驾于，比...更重要',
    '减缓',
    '寻找（食物）',
    '古怪的',
    '不足的，少的',
    '有的，有健康的',
    '禁止',
    '时髦的',
    '要求髙的<br/>费力的',
    '减弱',
    '礼貌',
    '友好，和谐',
    '掠夺',
    '过量',
    '复兴',
    '混杂，混合物',
    '过量',
    '少量',
    '缺乏'
];

var wordlist78 = [
    'pedestrian',
    'esoteric',
    'compelling',
    'erect',
    'list',
    'upright',
    'intransigent',
    'commence',
    'founder',
    'benign',
    'orthodox',
    'anomalous',
    'embody',
    'lag',
    'intriguing',
    'apprehend',
    'cursory',
    'intoxicate',
    'prevalent',
    'overwhelm',
    'preponderance',
    'annihilate',
    'nebulous',
    'concrete',
    'substantial',
    'venue',
    'retrenchment',
    'burgeon',
    'resurgence',
    'curtail'
];

var resultList78 = [
    '无聊的，普通的',
    '难懂的',
    '有趣的<br/>有说服力的',
    '笔直的',
    '倾斜',
    '垂直的<br/>正直的',
    '不妥协的，固执的',
    '开始',
    '彻底失败<br/>创始人，奠基人',
    '无害的<br/>温和的，善良的',
    '主流的<br/>符合传统的',
    '不寻常的，异常的',
    '体现',
    '衰弱',
    '非常有趣的',
    '逮捕<br/>理解<br/>害怕，恐惧',
    '草率的',
    '使...陶醉，沉醉',
    '流行的，普遍的',
    '完全覆盖，淹没',
    '优势，多数',
    '毁灭，毁坏',
    '模糊的，不清楚的',
    '真实的<br/>详细的',
    '大量的',
    '事件发生地点',
    '削减（尤指经费）',
    '繁荣，快速增长',
    '复苏',
    '削减'
];

var wordlist79 = [
    'trumpet',
    'thrift',
    'provenance',
    'undermine',
    'resurrect',
    'topple',
    'forsake',
    'pretentious',
    'oblivious',
    'uncompromising',
    'moralistic',
    'benevolent',
    'formidable',
    'impose',
    'innate',
    'intrude',
    'discard',
    'resumption',
    'stalemate',
    'setback',
    'vague',
    'requisite',
    'temporary',
    'faint',
    'endure',
    'dispel',
    'offset',
    'preclude',
    'disclose',
    'mitigate',
    'curtail',
    'divulge',
    'nomadic',
    'proclivity',
    'predilection',
    'disdain',
    'insatiable',
    'devious',
    'pretentious',
    'voracious',
    'cunning',
];

var resultList79 = [
    '鼓吹（本意为乐 器，小号）',
    '节检',
    '出处，起源',
    '削弱',
    '复兴',
    '推翻',
    '放弃',
    '炫耀的',
    '无意识的，遗忘的',
    '不妥协的，坚定的',
    '说教的',
    '仁慈的，慈善的',
    '恐怖的，可怕的,令人惊叹的<br/>艰巨的',
    '把......强加于',
    '天生的',
    '闯入',
    '抛弃，放弃',
    '恢复，重新开始',
    '僵局',
    '挫折',
    '模糊的',
    '必要的',
    '暂时的，临时的',
    '微弱的',
    '持续<br/>忍耐',
    '驱散，消除',
    '抵消',
    '阻止',
    '揭发，揭露',
    '减缓',
    '削减',
    '泄露',
    '游牧的',
    '倾向，偏好 ',
    '茂视，鄙视',
    '倾向，偏好 ',
    '无法满足的',
    '欺骗的<br/>弯曲的，蜿蜒的',
    '炫耀的',
    '贪婪的<br/>贪吃的',
    '狡猾机智的<br/>技艺局超的'
];

var wordlist80 = [
    'eclipse',
    'bolster',
    'corroborate',
    'outstrip',
    'invoke',
    'erudite',
    'contentious',
    'methodical',
    'diffident',
    'diligent',
    'timid',
    'assertive',
    'nettlesome',
    'incontrovertible',
    'attune',
    'eccentric',
    'predilection',
    'vacillate',
    'waver',
    'cowardice',
    'overshadow',
    'abate',
    'punctilious',
    'rigorous',
    'exculpate',
    'elite',
    'accomplish',
    'snappish',
    'tyrant',
    'umbrage',
    'expiation',
    'torpor',
    'collective',
    'overthrow',
    'placate',
    'appraise',
    'tangible',
    'palpable',
    'nebulous'
];

var resultList80 = [
    '使...不重要<br/>超出',
    '支持',
    '佐证，提供证据证 明',
    '胜出，超出',
    '实施<br/>恳求，祈求<br/>产生，造成',
    '博学的',
    '引起争议的<br/>爱争吵的',
    '有条理的',
    '缺乏自信的',
    '努力的，刻苦的',
    '胆小的，缺乏自信 的',
    '坚定自信的',
    '气人的，令人不快的',
    '不容质疑的',
    '使协调',
    '古怪的',
    '倾向，偏好',
    '摇摆不定，犹豫',
    '摇摆不定',
    '胆小',
    '超出，超过<br/>遮盖',
    '减退',
    '(对行为)谨慎小心的',
    '严格的<br/>细致的，准确的',
    '开脱罪责',
    '精英:',
    '完成，做成功',
    '厉声说话的，暴躁的',
    '暴君',
    '生气，不悦',
    '赎罪',
    '麻木，迟純，懒散',
    '集本的',
    '推翻',
    '安抚',
    '评估',
    '可感知的，实实在在的',
    '可感知的<br/>明显的',
    '模糊的，不清楚的'
];

var wordlist81 = [
    'civic',
    'contest',
    'trivial',
    'exclusive',
    'peccadillo',
    'violate',
    'reparation',
    'pretext',
    'inextricable',
    'masterpiece',
    'serendipitous',
    'precocious',
    'dedicate',
    'immerse',
    'verisimilitude',
    'rigorous',
    'apt',
    'countenance',
    'impugn',
    'evanescent',
    'polymath',
    'incongruous',
    'encyclopedic',
    'fleeting',
    'laypeople',
    'sordid',
    'fraught',
    'shoulder',
    'check',
    'stem',
    'manifest',
    'impregnable',
    'germane'
];

var resultList81 = [
    '公民的，市民的',
    '质疑',
    '不重要的',
    '独有的，排外的',
    '小过失',
    '违反',
    '修理<br/>赔偿',
    '借口',
    '纠缠不清的，无法解脱的',
    '杰作',
    '偶然的',
    '早熟的',
    '致力于，奉献于',
    '浸润，浸泡<br/>全心沉浸在...中',
    '逼真',
    '严格的<br/>细致的，准确的',
    '合适的<br/>有倾向的<br/>聪明的，灵巧的',
    '赞同<br/>支持，赞同',
    '(因人不诚实而)批评抨击',
    '短暂的',
    '博学的人',
    '不一致的',
    '(如大百科全书般）全面的',
    '短暂的',
    '外行',
    '肮脏的<br/>卑鄙的',
    '忧虑的',
    '承担',
    '阻止',
    '阻止，限制',
    '显然的，明显的<br/>清晰地展示，显露出',
    '坚固的',
    '相关的'
];

var wordlist82 = [
    'anthropomorphize',
    'empathy',
    'recast',
    'fickle',
    'stalwart',
    'solicitous',
    'pretentious',
    'whimsy',
    'cumulative',
    'dismiss',
    'endorse',
    'decipher',
    'credulous',
    'aesthetic',
    'ancillary',
    'stifle',
    'rationale',
    'gainsay',
    'judicious',
    'persevere',
    'prescient',
    'trigger',
    'offset',
    'integrate',
    'dedicate',
    'mass',
    'forgo',
    'glean',
    'undue',
    'scant',
    'dwindle',
    'alleviate',
    'block',
    'presage',
    'portend',
    'magnitude',
    'supple',
    'enormous'
];

var resultList82 = [
    '赋予人性',
    '感同身受',
    '彻底改动，重铸',
    '多变的',
    '坚定的，忠诚的',
    '关心的',
    '炫耀的',
    '突发奇想',
    '累积的',
    '让...离开；解雇<br/>不再考虑；拒绝',
    '公开支持',
    '解释，破译',
    '易受欺骗的',
    '美学的<br/>吸引人的',
    '辅助的',
    '抑制<br/>使窒息',
    '理甶',
    '否认',
    '有正确判断力的',
    '坚持',
    '预知的，有先见之明的',
    '触发',
    '抵消',
    '使完整，使成整体',
    '致力于，奉献于',
    '聚集',
    '放弃()',
    '慢慢收集',
    '过量的',
    '缺乏的',
    '减少，下降',
    '减缓',
    '阻碍，妨碍',
    '预测，预言',
    '预示',
    '大小，重量级',
    '灵活的',
    '大量的'
];

var wordlist = [
        wordlist1, wordlist2, wordlist3,
        wordlist4, wordlist5, wordlist6,
        wordlist7, wordlist8, wordlist9,
        wordlist10, wordlist11, wordlist12,
        wordlist13, wordlist14, wordlist15,
        wordlist16, wordlist17, wordlist18,
        wordlist19, wordlist20, wordlist21,
        wordlist22, wordlist23, wordlist24,
        wordlist25, wordlist26, wordlist27,
        wordlist28, wordlist29, wordlist30,
        wordlist31, wordlist32, wordlist33,
        wordlist34, wordlist35, wordlist36,
        wordlist37, wordlist38, wordlist39,
        wordlist40, wordlist41, wordlist42,
        wordlist43, wordlist44, wordlist45,
        wordlist46, wordlist47, wordlist48,
        wordlist49, wordlist50, wordlist51,
        wordlist52, wordlist53, wordlist54,
        wordlist55, wordlist56, wordlist57,
        wordlist58, wordlist59, wordlist60,
        wordlist61, wordlist62, wordlist63,
        wordlist64, wordlist65, wordlist66,
        wordlist67, wordlist68, wordlist69,
        wordlist70, wordlist71, wordlist72,
        wordlist73, wordlist74, wordlist75,
        wordlist76, wordlist77, wordlist78,
        wordlist79, wordlist80, wordlist81,
        wordlist82
    ],
    resultList = [
        resultList1, resultList2, resultList3,
        resultList4, resultList5, resultList6,
        resultList7, resultList8, resultList9,
        resultList10, resultList11, resultList12,
        resultList13, resultList14, resultList15,
        resultList16, resultList17, resultList18,
        resultList19, resultList20, resultList21,
        resultList22, resultList23, resultList24,
        resultList25, resultList26, resultList27,
        resultList28, resultList29, resultList30,
        resultList31, resultList32, resultList33,
        resultList34, resultList35, resultList36,
        resultList37, resultList38, resultList39,
        resultList40, resultList41, resultList42,
        resultList43, resultList44, resultList45,
        resultList46, resultList47, resultList48,
        resultList49, resultList50, resultList51,
        resultList52, resultList53, resultList54,
        resultList55, resultList56, resultList57,
        resultList58, resultList59, resultList60,
        resultList61, resultList62, resultList63,
        resultList64, resultList65, resultList66,
        resultList67, resultList68, resultList69,
        resultList70, resultList71, resultList72,
        resultList73, resultList74, resultList75,
        resultList76, resultList77, resultList78,
        resultList79, resultList80, resultList81,
        resultList82
];

var answerList = [];
